// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: community.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ListCommunitiesRequest_SortOrder int32

const (
	ListCommunitiesRequest_NEWEST     ListCommunitiesRequest_SortOrder = 0
	ListCommunitiesRequest_POPULARITY ListCommunitiesRequest_SortOrder = 1
)

// Enum value maps for ListCommunitiesRequest_SortOrder.
var (
	ListCommunitiesRequest_SortOrder_name = map[int32]string{
		0: "NEWEST",
		1: "POPULARITY",
	}
	ListCommunitiesRequest_SortOrder_value = map[string]int32{
		"NEWEST":     0,
		"POPULARITY": 1,
	}
)

func (x ListCommunitiesRequest_SortOrder) Enum() *ListCommunitiesRequest_SortOrder {
	p := new(ListCommunitiesRequest_SortOrder)
	*p = x
	return p
}

func (x ListCommunitiesRequest_SortOrder) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ListCommunitiesRequest_SortOrder) Descriptor() protoreflect.EnumDescriptor {
	return file_community_proto_enumTypes[0].Descriptor()
}

func (ListCommunitiesRequest_SortOrder) Type() protoreflect.EnumType {
	return &file_community_proto_enumTypes[0]
}

func (x ListCommunitiesRequest_SortOrder) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ListCommunitiesRequest_SortOrder.Descriptor instead.
func (ListCommunitiesRequest_SortOrder) EnumDescriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{10, 0}
}

type ValidateCommunitySlugRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCommunitySlugRequest) Reset() {
	*x = ValidateCommunitySlugRequest{}
	mi := &file_community_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCommunitySlugRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCommunitySlugRequest) ProtoMessage() {}

func (x *ValidateCommunitySlugRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCommunitySlugRequest.ProtoReflect.Descriptor instead.
func (*ValidateCommunitySlugRequest) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{0}
}

func (x *ValidateCommunitySlugRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

type ValidateCommunitySlugResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateCommunitySlugResponse) Reset() {
	*x = ValidateCommunitySlugResponse{}
	mi := &file_community_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateCommunitySlugResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateCommunitySlugResponse) ProtoMessage() {}

func (x *ValidateCommunitySlugResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateCommunitySlugResponse.ProtoReflect.Descriptor instead.
func (*ValidateCommunitySlugResponse) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{1}
}

type CreateCommunityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Slug          string                 `protobuf:"bytes,1,opt,name=slug,proto3" json:"slug,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`               // 3-50 chars
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"` // max 500 chars
	Rules         string                 `protobuf:"bytes,4,opt,name=rules,proto3" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommunityRequest) Reset() {
	*x = CreateCommunityRequest{}
	mi := &file_community_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommunityRequest) ProtoMessage() {}

func (x *CreateCommunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommunityRequest.ProtoReflect.Descriptor instead.
func (*CreateCommunityRequest) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{2}
}

func (x *CreateCommunityRequest) GetSlug() string {
	if x != nil {
		return x.Slug
	}
	return ""
}

func (x *CreateCommunityRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateCommunityRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateCommunityRequest) GetRules() string {
	if x != nil {
		return x.Rules
	}
	return ""
}

type CreateCommunityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Community     *Community             `protobuf:"bytes,1,opt,name=community,proto3" json:"community,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateCommunityResponse) Reset() {
	*x = CreateCommunityResponse{}
	mi := &file_community_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateCommunityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateCommunityResponse) ProtoMessage() {}

func (x *CreateCommunityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateCommunityResponse.ProtoReflect.Descriptor instead.
func (*CreateCommunityResponse) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{3}
}

func (x *CreateCommunityResponse) GetCommunity() *Community {
	if x != nil {
		return x.Community
	}
	return nil
}

type GetCommunityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommunityRequest) Reset() {
	*x = GetCommunityRequest{}
	mi := &file_community_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommunityRequest) ProtoMessage() {}

func (x *GetCommunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommunityRequest.ProtoReflect.Descriptor instead.
func (*GetCommunityRequest) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{4}
}

func (x *GetCommunityRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

type GetCommunityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Community     *Community             `protobuf:"bytes,1,opt,name=community,proto3" json:"community,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCommunityResponse) Reset() {
	*x = GetCommunityResponse{}
	mi := &file_community_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCommunityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCommunityResponse) ProtoMessage() {}

func (x *GetCommunityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCommunityResponse.ProtoReflect.Descriptor instead.
func (*GetCommunityResponse) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{5}
}

func (x *GetCommunityResponse) GetCommunity() *Community {
	if x != nil {
		return x.Community
	}
	return nil
}

type UpdateCommunityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description   *string                `protobuf:"bytes,3,opt,name=description,proto3,oneof" json:"description,omitempty"`
	Rules         *string                `protobuf:"bytes,4,opt,name=rules,proto3,oneof" json:"rules,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommunityRequest) Reset() {
	*x = UpdateCommunityRequest{}
	mi := &file_community_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommunityRequest) ProtoMessage() {}

func (x *UpdateCommunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommunityRequest.ProtoReflect.Descriptor instead.
func (*UpdateCommunityRequest) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateCommunityRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *UpdateCommunityRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateCommunityRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateCommunityRequest) GetRules() string {
	if x != nil && x.Rules != nil {
		return *x.Rules
	}
	return ""
}

type UpdateCommunityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Community     *Community             `protobuf:"bytes,1,opt,name=community,proto3" json:"community,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateCommunityResponse) Reset() {
	*x = UpdateCommunityResponse{}
	mi := &file_community_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateCommunityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateCommunityResponse) ProtoMessage() {}

func (x *UpdateCommunityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateCommunityResponse.ProtoReflect.Descriptor instead.
func (*UpdateCommunityResponse) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateCommunityResponse) GetCommunity() *Community {
	if x != nil {
		return x.Community
	}
	return nil
}

type ArchiveCommunityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	Confirm       bool                   `protobuf:"varint,2,opt,name=confirm,proto3" json:"confirm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveCommunityRequest) Reset() {
	*x = ArchiveCommunityRequest{}
	mi := &file_community_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveCommunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveCommunityRequest) ProtoMessage() {}

func (x *ArchiveCommunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveCommunityRequest.ProtoReflect.Descriptor instead.
func (*ArchiveCommunityRequest) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{8}
}

func (x *ArchiveCommunityRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *ArchiveCommunityRequest) GetConfirm() bool {
	if x != nil {
		return x.Confirm
	}
	return false
}

type ArchiveCommunityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ArchiveCommunityResponse) Reset() {
	*x = ArchiveCommunityResponse{}
	mi := &file_community_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ArchiveCommunityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArchiveCommunityResponse) ProtoMessage() {}

func (x *ArchiveCommunityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArchiveCommunityResponse.ProtoReflect.Descriptor instead.
func (*ArchiveCommunityResponse) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{9}
}

type ListCommunitiesRequest struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Cursor        string                           `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                            `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	SortBy        ListCommunitiesRequest_SortOrder `protobuf:"varint,3,opt,name=sort_by,json=sortBy,proto3,enum=proto.ListCommunitiesRequest_SortOrder" json:"sort_by,omitempty"`
	IncludeBanned bool                             `protobuf:"varint,4,opt,name=include_banned,json=includeBanned,proto3" json:"include_banned,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommunitiesRequest) Reset() {
	*x = ListCommunitiesRequest{}
	mi := &file_community_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommunitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommunitiesRequest) ProtoMessage() {}

func (x *ListCommunitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommunitiesRequest.ProtoReflect.Descriptor instead.
func (*ListCommunitiesRequest) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{10}
}

func (x *ListCommunitiesRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListCommunitiesRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *ListCommunitiesRequest) GetSortBy() ListCommunitiesRequest_SortOrder {
	if x != nil {
		return x.SortBy
	}
	return ListCommunitiesRequest_NEWEST
}

func (x *ListCommunitiesRequest) GetIncludeBanned() bool {
	if x != nil {
		return x.IncludeBanned
	}
	return false
}

type ListCommunitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Communities   []*Community           `protobuf:"bytes,1,rep,name=communities,proto3" json:"communities,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCommunitiesResponse) Reset() {
	*x = ListCommunitiesResponse{}
	mi := &file_community_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCommunitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCommunitiesResponse) ProtoMessage() {}

func (x *ListCommunitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCommunitiesResponse.ProtoReflect.Descriptor instead.
func (*ListCommunitiesResponse) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{11}
}

func (x *ListCommunitiesResponse) GetCommunities() []*Community {
	if x != nil {
		return x.Communities
	}
	return nil
}

func (x *ListCommunitiesResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListCommunitiesResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type JoinCommunityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinCommunityRequest) Reset() {
	*x = JoinCommunityRequest{}
	mi := &file_community_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinCommunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinCommunityRequest) ProtoMessage() {}

func (x *JoinCommunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinCommunityRequest.ProtoReflect.Descriptor instead.
func (*JoinCommunityRequest) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{12}
}

func (x *JoinCommunityRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

type JoinCommunityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinCommunityResponse) Reset() {
	*x = JoinCommunityResponse{}
	mi := &file_community_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinCommunityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinCommunityResponse) ProtoMessage() {}

func (x *JoinCommunityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinCommunityResponse.ProtoReflect.Descriptor instead.
func (*JoinCommunityResponse) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{13}
}

type LeaveCommunityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveCommunityRequest) Reset() {
	*x = LeaveCommunityRequest{}
	mi := &file_community_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveCommunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveCommunityRequest) ProtoMessage() {}

func (x *LeaveCommunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveCommunityRequest.ProtoReflect.Descriptor instead.
func (*LeaveCommunityRequest) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{14}
}

func (x *LeaveCommunityRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

type LeaveCommunityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaveCommunityResponse) Reset() {
	*x = LeaveCommunityResponse{}
	mi := &file_community_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaveCommunityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaveCommunityResponse) ProtoMessage() {}

func (x *LeaveCommunityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaveCommunityResponse.ProtoReflect.Descriptor instead.
func (*LeaveCommunityResponse) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{15}
}

type BanCommunityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanCommunityRequest) Reset() {
	*x = BanCommunityRequest{}
	mi := &file_community_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanCommunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanCommunityRequest) ProtoMessage() {}

func (x *BanCommunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanCommunityRequest.ProtoReflect.Descriptor instead.
func (*BanCommunityRequest) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{16}
}

func (x *BanCommunityRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *BanCommunityRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type BanCommunityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BanCommunityResponse) Reset() {
	*x = BanCommunityResponse{}
	mi := &file_community_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BanCommunityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BanCommunityResponse) ProtoMessage() {}

func (x *BanCommunityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BanCommunityResponse.ProtoReflect.Descriptor instead.
func (*BanCommunityResponse) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{17}
}

type UnbanCommunityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanCommunityRequest) Reset() {
	*x = UnbanCommunityRequest{}
	mi := &file_community_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanCommunityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanCommunityRequest) ProtoMessage() {}

func (x *UnbanCommunityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanCommunityRequest.ProtoReflect.Descriptor instead.
func (*UnbanCommunityRequest) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{18}
}

func (x *UnbanCommunityRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

type UnbanCommunityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnbanCommunityResponse) Reset() {
	*x = UnbanCommunityResponse{}
	mi := &file_community_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnbanCommunityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnbanCommunityResponse) ProtoMessage() {}

func (x *UnbanCommunityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnbanCommunityResponse.ProtoReflect.Descriptor instead.
func (*UnbanCommunityResponse) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{19}
}

type TransferCommunityOwnershipRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CommunityId   string                 `protobuf:"bytes,1,opt,name=community_id,json=communityId,proto3" json:"community_id,omitempty"`
	NewOwnerId    string                 `protobuf:"bytes,2,opt,name=new_owner_id,json=newOwnerId,proto3" json:"new_owner_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferCommunityOwnershipRequest) Reset() {
	*x = TransferCommunityOwnershipRequest{}
	mi := &file_community_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferCommunityOwnershipRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferCommunityOwnershipRequest) ProtoMessage() {}

func (x *TransferCommunityOwnershipRequest) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferCommunityOwnershipRequest.ProtoReflect.Descriptor instead.
func (*TransferCommunityOwnershipRequest) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{20}
}

func (x *TransferCommunityOwnershipRequest) GetCommunityId() string {
	if x != nil {
		return x.CommunityId
	}
	return ""
}

func (x *TransferCommunityOwnershipRequest) GetNewOwnerId() string {
	if x != nil {
		return x.NewOwnerId
	}
	return ""
}

type TransferCommunityOwnershipResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TransferCommunityOwnershipResponse) Reset() {
	*x = TransferCommunityOwnershipResponse{}
	mi := &file_community_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TransferCommunityOwnershipResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferCommunityOwnershipResponse) ProtoMessage() {}

func (x *TransferCommunityOwnershipResponse) ProtoReflect() protoreflect.Message {
	mi := &file_community_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferCommunityOwnershipResponse.ProtoReflect.Descriptor instead.
func (*TransferCommunityOwnershipResponse) Descriptor() ([]byte, []int) {
	return file_community_proto_rawDescGZIP(), []int{21}
}

var File_community_proto protoreflect.FileDescriptor

const file_community_proto_rawDesc = "" +
	"\n" +
	"\x0fcommunity.proto\x12\x05proto\x1a\fentity.proto\x1a\x1cgoogle/api/annotations.proto\"2\n" +
	"\x1cValidateCommunitySlugRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\"\x1f\n" +
	"\x1dValidateCommunitySlugResponse\"x\n" +
	"\x16CreateCommunityRequest\x12\x12\n" +
	"\x04slug\x18\x01 \x01(\tR\x04slug\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05rules\x18\x04 \x01(\tR\x05rules\"I\n" +
	"\x17CreateCommunityResponse\x12.\n" +
	"\tcommunity\x18\x01 \x01(\v2\x10.proto.CommunityR\tcommunity\"8\n" +
	"\x13GetCommunityRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\"F\n" +
	"\x14GetCommunityResponse\x12.\n" +
	"\tcommunity\x18\x01 \x01(\v2\x10.proto.CommunityR\tcommunity\"\xb9\x01\n" +
	"\x16UpdateCommunityRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\x12\x17\n" +
	"\x04name\x18\x02 \x01(\tH\x00R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x03 \x01(\tH\x01R\vdescription\x88\x01\x01\x12\x19\n" +
	"\x05rules\x18\x04 \x01(\tH\x02R\x05rules\x88\x01\x01B\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\b\n" +
	"\x06_rules\"I\n" +
	"\x17UpdateCommunityResponse\x12.\n" +
	"\tcommunity\x18\x01 \x01(\v2\x10.proto.CommunityR\tcommunity\"V\n" +
	"\x17ArchiveCommunityRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\x12\x18\n" +
	"\aconfirm\x18\x02 \x01(\bR\aconfirm\"\x1a\n" +
	"\x18ArchiveCommunityResponse\"\xd8\x01\n" +
	"\x16ListCommunitiesRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12@\n" +
	"\asort_by\x18\x03 \x01(\x0e2'.proto.ListCommunitiesRequest.SortOrderR\x06sortBy\x12%\n" +
	"\x0einclude_banned\x18\x04 \x01(\bR\rincludeBanned\"'\n" +
	"\tSortOrder\x12\n" +
	"\n" +
	"\x06NEWEST\x10\x00\x12\x0e\n" +
	"\n" +
	"POPULARITY\x10\x01\"\x89\x01\n" +
	"\x17ListCommunitiesResponse\x122\n" +
	"\vcommunities\x18\x01 \x03(\v2\x10.proto.CommunityR\vcommunities\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"9\n" +
	"\x14JoinCommunityRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\"\x17\n" +
	"\x15JoinCommunityResponse\":\n" +
	"\x15LeaveCommunityRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\"\x18\n" +
	"\x16LeaveCommunityResponse\"P\n" +
	"\x13BanCommunityRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\x12\x16\n" +
	"\x06reason\x18\x02 \x01(\tR\x06reason\"\x16\n" +
	"\x14BanCommunityResponse\":\n" +
	"\x15UnbanCommunityRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\"\x18\n" +
	"\x16UnbanCommunityResponse\"h\n" +
	"!TransferCommunityOwnershipRequest\x12!\n" +
	"\fcommunity_id\x18\x01 \x01(\tR\vcommunityId\x12 \n" +
	"\fnew_owner_id\x18\x02 \x01(\tR\n" +
	"newOwnerId\"$\n" +
	"\"TransferCommunityOwnershipResponse2\x9b\n" +
	"\n" +
	"\x10CommunityService\x12\x89\x01\n" +
	"\x15ValidateCommunitySlug\x12#.proto.ValidateCommunitySlugRequest\x1a$.proto.ValidateCommunitySlugResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\"\x1a/communities/validate-slug\x12`\n" +
	"\x06Create\x12\x1d.proto.CreateCommunityRequest\x1a\x1e.proto.CreateCommunityResponse\"\x17\x82\xd3\xe4\x93\x02\x11:\x01*\"\f/communities\x12c\n" +
	"\x03Get\x12\x1a.proto.GetCommunityRequest\x1a\x1b.proto.GetCommunityResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/communities/{community_id}\x12o\n" +
	"\x06Update\x12\x1d.proto.UpdateCommunityRequest\x1a\x1e.proto.UpdateCommunityResponse\"&\x82\xd3\xe4\x93\x02 :\x01*2\x1b/communities/{community_id}\x12z\n" +
	"\aArchive\x12\x1e.proto.ArchiveCommunityRequest\x1a\x1f.proto.ArchiveCommunityResponse\".\x82\xd3\xe4\x93\x02(:\x01*\"#/communities/{community_id}/archive\x12f\n" +
	"\x0fListCommunities\x12\x1d.proto.ListCommunitiesRequest\x1a\x1e.proto.ListCommunitiesResponse\"\x14\x82\xd3\xe4\x93\x02\x0e\x12\f/communities\x12k\n" +
	"\x04Join\x12\x1b.proto.JoinCommunityRequest\x1a\x1c.proto.JoinCommunityResponse\"(\x82\xd3\xe4\x93\x02\"\" /communities/{community_id}/join\x12o\n" +
	"\x05Leave\x12\x1c.proto.LeaveCommunityRequest\x1a\x1d.proto.LeaveCommunityResponse\")\x82\xd3\xe4\x93\x02#\"!/communities/{community_id}/leave\x12j\n" +
	"\x03Ban\x12\x1a.proto.BanCommunityRequest\x1a\x1b.proto.BanCommunityResponse\"*\x82\xd3\xe4\x93\x02$:\x01*\"\x1f/communities/{community_id}/ban\x12o\n" +
	"\x05Unban\x12\x1c.proto.UnbanCommunityRequest\x1a\x1d.proto.UnbanCommunityResponse\")\x82\xd3\xe4\x93\x02#\"!/communities/{community_id}/unban\x12\xa3\x01\n" +
	"\x11TransferOwnership\x12(.proto.TransferCommunityOwnershipRequest\x1a).proto.TransferCommunityOwnershipResponse\"9\x82\xd3\xe4\x93\x023:\x01*\"./communities/{community_id}/transfer-ownershipB\bZ\x06/protob\x06proto3"

var (
	file_community_proto_rawDescOnce sync.Once
	file_community_proto_rawDescData []byte
)

func file_community_proto_rawDescGZIP() []byte {
	file_community_proto_rawDescOnce.Do(func() {
		file_community_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_community_proto_rawDesc), len(file_community_proto_rawDesc)))
	})
	return file_community_proto_rawDescData
}

var file_community_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_community_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_community_proto_goTypes = []any{
	(ListCommunitiesRequest_SortOrder)(0),      // 0: proto.ListCommunitiesRequest.SortOrder
	(*ValidateCommunitySlugRequest)(nil),       // 1: proto.ValidateCommunitySlugRequest
	(*ValidateCommunitySlugResponse)(nil),      // 2: proto.ValidateCommunitySlugResponse
	(*CreateCommunityRequest)(nil),             // 3: proto.CreateCommunityRequest
	(*CreateCommunityResponse)(nil),            // 4: proto.CreateCommunityResponse
	(*GetCommunityRequest)(nil),                // 5: proto.GetCommunityRequest
	(*GetCommunityResponse)(nil),               // 6: proto.GetCommunityResponse
	(*UpdateCommunityRequest)(nil),             // 7: proto.UpdateCommunityRequest
	(*UpdateCommunityResponse)(nil),            // 8: proto.UpdateCommunityResponse
	(*ArchiveCommunityRequest)(nil),            // 9: proto.ArchiveCommunityRequest
	(*ArchiveCommunityResponse)(nil),           // 10: proto.ArchiveCommunityResponse
	(*ListCommunitiesRequest)(nil),             // 11: proto.ListCommunitiesRequest
	(*ListCommunitiesResponse)(nil),            // 12: proto.ListCommunitiesResponse
	(*JoinCommunityRequest)(nil),               // 13: proto.JoinCommunityRequest
	(*JoinCommunityResponse)(nil),              // 14: proto.JoinCommunityResponse
	(*LeaveCommunityRequest)(nil),              // 15: proto.LeaveCommunityRequest
	(*LeaveCommunityResponse)(nil),             // 16: proto.LeaveCommunityResponse
	(*BanCommunityRequest)(nil),                // 17: proto.BanCommunityRequest
	(*BanCommunityResponse)(nil),               // 18: proto.BanCommunityResponse
	(*UnbanCommunityRequest)(nil),              // 19: proto.UnbanCommunityRequest
	(*UnbanCommunityResponse)(nil),             // 20: proto.UnbanCommunityResponse
	(*TransferCommunityOwnershipRequest)(nil),  // 21: proto.TransferCommunityOwnershipRequest
	(*TransferCommunityOwnershipResponse)(nil), // 22: proto.TransferCommunityOwnershipResponse
	(*Community)(nil),                          // 23: proto.Community
}
var file_community_proto_depIdxs = []int32{
	23, // 0: proto.CreateCommunityResponse.community:type_name -> proto.Community
	23, // 1: proto.GetCommunityResponse.community:type_name -> proto.Community
	23, // 2: proto.UpdateCommunityResponse.community:type_name -> proto.Community
	0,  // 3: proto.ListCommunitiesRequest.sort_by:type_name -> proto.ListCommunitiesRequest.SortOrder
	23, // 4: proto.ListCommunitiesResponse.communities:type_name -> proto.Community
	1,  // 5: proto.CommunityService.ValidateCommunitySlug:input_type -> proto.ValidateCommunitySlugRequest
	3,  // 6: proto.CommunityService.Create:input_type -> proto.CreateCommunityRequest
	5,  // 7: proto.CommunityService.Get:input_type -> proto.GetCommunityRequest
	7,  // 8: proto.CommunityService.Update:input_type -> proto.UpdateCommunityRequest
	9,  // 9: proto.CommunityService.Archive:input_type -> proto.ArchiveCommunityRequest
	11, // 10: proto.CommunityService.ListCommunities:input_type -> proto.ListCommunitiesRequest
	13, // 11: proto.CommunityService.Join:input_type -> proto.JoinCommunityRequest
	15, // 12: proto.CommunityService.Leave:input_type -> proto.LeaveCommunityRequest
	17, // 13: proto.CommunityService.Ban:input_type -> proto.BanCommunityRequest
	19, // 14: proto.CommunityService.Unban:input_type -> proto.UnbanCommunityRequest
	21, // 15: proto.CommunityService.TransferOwnership:input_type -> proto.TransferCommunityOwnershipRequest
	2,  // 16: proto.CommunityService.ValidateCommunitySlug:output_type -> proto.ValidateCommunitySlugResponse
	4,  // 17: proto.CommunityService.Create:output_type -> proto.CreateCommunityResponse
	6,  // 18: proto.CommunityService.Get:output_type -> proto.GetCommunityResponse
	8,  // 19: proto.CommunityService.Update:output_type -> proto.UpdateCommunityResponse
	10, // 20: proto.CommunityService.Archive:output_type -> proto.ArchiveCommunityResponse
	12, // 21: proto.CommunityService.ListCommunities:output_type -> proto.ListCommunitiesResponse
	14, // 22: proto.CommunityService.Join:output_type -> proto.JoinCommunityResponse
	16, // 23: proto.CommunityService.Leave:output_type -> proto.LeaveCommunityResponse
	18, // 24: proto.CommunityService.Ban:output_type -> proto.BanCommunityResponse
	20, // 25: proto.CommunityService.Unban:output_type -> proto.UnbanCommunityResponse
	22, // 26: proto.CommunityService.TransferOwnership:output_type -> proto.TransferCommunityOwnershipResponse
	16, // [16:27] is the sub-list for method output_type
	5,  // [5:16] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_community_proto_init() }
func file_community_proto_init() {
	if File_community_proto != nil {
		return
	}
	file_entity_proto_init()
	file_community_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_community_proto_rawDesc), len(file_community_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_community_proto_goTypes,
		DependencyIndexes: file_community_proto_depIdxs,
		EnumInfos:         file_community_proto_enumTypes,
		MessageInfos:      file_community_proto_msgTypes,
	}.Build()
	File_community_proto = out.File
	file_community_proto_goTypes = nil
	file_community_proto_depIdxs = nil
}
