// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: feed.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TimePeriod int32

const (
	TimePeriod_TIME_PERIOD_UNSPECIFIED TimePeriod = 0
	TimePeriod_TIME_PERIOD_TODAY       TimePeriod = 1
	TimePeriod_TIME_PERIOD_WEEK        TimePeriod = 2
	TimePeriod_TIME_PERIOD_MONTH       TimePeriod = 3
	TimePeriod_TIME_PERIOD_YEAR        TimePeriod = 4
	TimePeriod_TIME_PERIOD_ALL_TIME    TimePeriod = 5
)

// Enum value maps for TimePeriod.
var (
	TimePeriod_name = map[int32]string{
		0: "TIME_PERIOD_UNSPECIFIED",
		1: "TIME_PERIOD_TODAY",
		2: "TIME_PERIOD_WEEK",
		3: "TIME_PERIOD_MONTH",
		4: "TIME_PERIOD_YEAR",
		5: "TIME_PERIOD_ALL_TIME",
	}
	TimePeriod_value = map[string]int32{
		"TIME_PERIOD_UNSPECIFIED": 0,
		"TIME_PERIOD_TODAY":       1,
		"TIME_PERIOD_WEEK":        2,
		"TIME_PERIOD_MONTH":       3,
		"TIME_PERIOD_YEAR":        4,
		"TIME_PERIOD_ALL_TIME":    5,
	}
)

func (x TimePeriod) Enum() *TimePeriod {
	p := new(TimePeriod)
	*p = x
	return p
}

func (x TimePeriod) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TimePeriod) Descriptor() protoreflect.EnumDescriptor {
	return file_feed_proto_enumTypes[0].Descriptor()
}

func (TimePeriod) Type() protoreflect.EnumType {
	return &file_feed_proto_enumTypes[0]
}

func (x TimePeriod) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TimePeriod.Descriptor instead.
func (TimePeriod) EnumDescriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{0}
}

type GetFeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TimePeriod    TimePeriod             `protobuf:"varint,1,opt,name=time_period,json=timePeriod,proto3,enum=proto.TimePeriod" json:"time_period,omitempty"`
	CommunityId   *string                `protobuf:"bytes,2,opt,name=community_id,json=communityId,proto3,oneof" json:"community_id,omitempty"` // if empty, global feed
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedRequest) Reset() {
	*x = GetFeedRequest{}
	mi := &file_feed_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedRequest) ProtoMessage() {}

func (x *GetFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedRequest.ProtoReflect.Descriptor instead.
func (*GetFeedRequest) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{0}
}

func (x *GetFeedRequest) GetTimePeriod() TimePeriod {
	if x != nil {
		return x.TimePeriod
	}
	return TimePeriod_TIME_PERIOD_UNSPECIFIED
}

func (x *GetFeedRequest) GetCommunityId() string {
	if x != nil && x.CommunityId != nil {
		return *x.CommunityId
	}
	return ""
}

func (x *GetFeedRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *GetFeedRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetFeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*Post                `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetFeedResponse) Reset() {
	*x = GetFeedResponse{}
	mi := &file_feed_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetFeedResponse) ProtoMessage() {}

func (x *GetFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetFeedResponse.ProtoReflect.Descriptor instead.
func (*GetFeedResponse) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{1}
}

func (x *GetFeedResponse) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *GetFeedResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *GetFeedResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type GetPersonalizedFeedRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Cursor        string                 `protobuf:"bytes,1,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPersonalizedFeedRequest) Reset() {
	*x = GetPersonalizedFeedRequest{}
	mi := &file_feed_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPersonalizedFeedRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonalizedFeedRequest) ProtoMessage() {}

func (x *GetPersonalizedFeedRequest) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonalizedFeedRequest.ProtoReflect.Descriptor instead.
func (*GetPersonalizedFeedRequest) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{2}
}

func (x *GetPersonalizedFeedRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *GetPersonalizedFeedRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetPersonalizedFeedResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Posts         []*Post                `protobuf:"bytes,1,rep,name=posts,proto3" json:"posts,omitempty"` // from followed users + joined communities
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPersonalizedFeedResponse) Reset() {
	*x = GetPersonalizedFeedResponse{}
	mi := &file_feed_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPersonalizedFeedResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPersonalizedFeedResponse) ProtoMessage() {}

func (x *GetPersonalizedFeedResponse) ProtoReflect() protoreflect.Message {
	mi := &file_feed_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPersonalizedFeedResponse.ProtoReflect.Descriptor instead.
func (*GetPersonalizedFeedResponse) Descriptor() ([]byte, []int) {
	return file_feed_proto_rawDescGZIP(), []int{3}
}

func (x *GetPersonalizedFeedResponse) GetPosts() []*Post {
	if x != nil {
		return x.Posts
	}
	return nil
}

func (x *GetPersonalizedFeedResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *GetPersonalizedFeedResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_feed_proto protoreflect.FileDescriptor

const file_feed_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"feed.proto\x12\x05proto\x1a\fentity.proto\x1a\x1cgoogle/api/annotations.proto\"\xab\x01\n" +
	"\x0eGetFeedRequest\x122\n" +
	"\vtime_period\x18\x01 \x01(\x0e2\x11.proto.TimePeriodR\n" +
	"timePeriod\x12&\n" +
	"\fcommunity_id\x18\x02 \x01(\tH\x00R\vcommunityId\x88\x01\x01\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limitB\x0f\n" +
	"\r_community_id\"p\n" +
	"\x0fGetFeedResponse\x12!\n" +
	"\x05posts\x18\x01 \x03(\v2\v.proto.PostR\x05posts\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"J\n" +
	"\x1aGetPersonalizedFeedRequest\x12\x16\n" +
	"\x06cursor\x18\x01 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\"|\n" +
	"\x1bGetPersonalizedFeedResponse\x12!\n" +
	"\x05posts\x18\x01 \x03(\v2\v.proto.PostR\x05posts\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore*\x9d\x01\n" +
	"\n" +
	"TimePeriod\x12\x1b\n" +
	"\x17TIME_PERIOD_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11TIME_PERIOD_TODAY\x10\x01\x12\x14\n" +
	"\x10TIME_PERIOD_WEEK\x10\x02\x12\x15\n" +
	"\x11TIME_PERIOD_MONTH\x10\x03\x12\x14\n" +
	"\x10TIME_PERIOD_YEAR\x10\x04\x12\x18\n" +
	"\x14TIME_PERIOD_ALL_TIME\x10\x052\xd0\x01\n" +
	"\vFeedService\x12G\n" +
	"\aGetFeed\x12\x15.proto.GetFeedRequest\x1a\x16.proto.GetFeedResponse\"\r\x82\xd3\xe4\x93\x02\a\x12\x05/feed\x12x\n" +
	"\x13GetPersonalizedFeed\x12!.proto.GetPersonalizedFeedRequest\x1a\".proto.GetPersonalizedFeedResponse\"\x1a\x82\xd3\xe4\x93\x02\x14\x12\x12/feed/personalizedB\bZ\x06/protob\x06proto3"

var (
	file_feed_proto_rawDescOnce sync.Once
	file_feed_proto_rawDescData []byte
)

func file_feed_proto_rawDescGZIP() []byte {
	file_feed_proto_rawDescOnce.Do(func() {
		file_feed_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_feed_proto_rawDesc), len(file_feed_proto_rawDesc)))
	})
	return file_feed_proto_rawDescData
}

var file_feed_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_feed_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_feed_proto_goTypes = []any{
	(TimePeriod)(0),                     // 0: proto.TimePeriod
	(*GetFeedRequest)(nil),              // 1: proto.GetFeedRequest
	(*GetFeedResponse)(nil),             // 2: proto.GetFeedResponse
	(*GetPersonalizedFeedRequest)(nil),  // 3: proto.GetPersonalizedFeedRequest
	(*GetPersonalizedFeedResponse)(nil), // 4: proto.GetPersonalizedFeedResponse
	(*Post)(nil),                        // 5: proto.Post
}
var file_feed_proto_depIdxs = []int32{
	0, // 0: proto.GetFeedRequest.time_period:type_name -> proto.TimePeriod
	5, // 1: proto.GetFeedResponse.posts:type_name -> proto.Post
	5, // 2: proto.GetPersonalizedFeedResponse.posts:type_name -> proto.Post
	1, // 3: proto.FeedService.GetFeed:input_type -> proto.GetFeedRequest
	3, // 4: proto.FeedService.GetPersonalizedFeed:input_type -> proto.GetPersonalizedFeedRequest
	2, // 5: proto.FeedService.GetFeed:output_type -> proto.GetFeedResponse
	4, // 6: proto.FeedService.GetPersonalizedFeed:output_type -> proto.GetPersonalizedFeedResponse
	5, // [5:7] is the sub-list for method output_type
	3, // [3:5] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_feed_proto_init() }
func file_feed_proto_init() {
	if File_feed_proto != nil {
		return
	}
	file_entity_proto_init()
	file_feed_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_feed_proto_rawDesc), len(file_feed_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_feed_proto_goTypes,
		DependencyIndexes: file_feed_proto_depIdxs,
		EnumInfos:         file_feed_proto_enumTypes,
		MessageInfos:      file_feed_proto_msgTypes,
	}.Build()
	File_feed_proto = out.File
	file_feed_proto_goTypes = nil
	file_feed_proto_depIdxs = nil
}
