// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: media.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RelationType int32

const (
	RelationType_MEDIA_TYPE_UNSPECIFIED        RelationType = 0
	RelationType_MEDIA_TYPE_USER_AVATAR        RelationType = 1
	RelationType_MEDIA_TYPE_USER_BANNER        RelationType = 2
	RelationType_MEDIA_TYPE_COMMENT_ATTACHMENT RelationType = 3
	RelationType_MEDIA_TYPE_PLATFORM_LOGO      RelationType = 4
	RelationType_MEDIA_TYPE_PLATFORM_BANNER    RelationType = 5
	RelationType_MEDIA_TYPE_COMMUNITY_LOGO     RelationType = 6
	RelationType_MEDIA_TYPE_COMMUNITY_BANNER   RelationType = 7
)

// Enum value maps for RelationType.
var (
	RelationType_name = map[int32]string{
		0: "MEDIA_TYPE_UNSPECIFIED",
		1: "MEDIA_TYPE_USER_AVATAR",
		2: "MEDIA_TYPE_USER_BANNER",
		3: "MEDIA_TYPE_COMMENT_ATTACHMENT",
		4: "MEDIA_TYPE_PLATFORM_LOGO",
		5: "MEDIA_TYPE_PLATFORM_BANNER",
		6: "MEDIA_TYPE_COMMUNITY_LOGO",
		7: "MEDIA_TYPE_COMMUNITY_BANNER",
	}
	RelationType_value = map[string]int32{
		"MEDIA_TYPE_UNSPECIFIED":        0,
		"MEDIA_TYPE_USER_AVATAR":        1,
		"MEDIA_TYPE_USER_BANNER":        2,
		"MEDIA_TYPE_COMMENT_ATTACHMENT": 3,
		"MEDIA_TYPE_PLATFORM_LOGO":      4,
		"MEDIA_TYPE_PLATFORM_BANNER":    5,
		"MEDIA_TYPE_COMMUNITY_LOGO":     6,
		"MEDIA_TYPE_COMMUNITY_BANNER":   7,
	}
)

func (x RelationType) Enum() *RelationType {
	p := new(RelationType)
	*p = x
	return p
}

func (x RelationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RelationType) Descriptor() protoreflect.EnumDescriptor {
	return file_media_proto_enumTypes[0].Descriptor()
}

func (RelationType) Type() protoreflect.EnumType {
	return &file_media_proto_enumTypes[0]
}

func (x RelationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RelationType.Descriptor instead.
func (RelationType) EnumDescriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{0}
}

type FileType int32

const (
	FileType_FILE_TYPE_UNSPECIFIED FileType = 0
	FileType_FILE_TYPE_IMAGE       FileType = 1 // max 10MB
	FileType_FILE_TYPE_VIDEO       FileType = 2 // max 100MB
	FileType_FILE_TYPE_AUDIO       FileType = 3 // max 20MB
	FileType_FILE_TYPE_GIF         FileType = 4 // max 15MB
)

// Enum value maps for FileType.
var (
	FileType_name = map[int32]string{
		0: "FILE_TYPE_UNSPECIFIED",
		1: "FILE_TYPE_IMAGE",
		2: "FILE_TYPE_VIDEO",
		3: "FILE_TYPE_AUDIO",
		4: "FILE_TYPE_GIF",
	}
	FileType_value = map[string]int32{
		"FILE_TYPE_UNSPECIFIED": 0,
		"FILE_TYPE_IMAGE":       1,
		"FILE_TYPE_VIDEO":       2,
		"FILE_TYPE_AUDIO":       3,
		"FILE_TYPE_GIF":         4,
	}
)

func (x FileType) Enum() *FileType {
	p := new(FileType)
	*p = x
	return p
}

func (x FileType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FileType) Descriptor() protoreflect.EnumDescriptor {
	return file_media_proto_enumTypes[1].Descriptor()
}

func (FileType) Type() protoreflect.EnumType {
	return &file_media_proto_enumTypes[1]
}

func (x FileType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FileType.Descriptor instead.
func (FileType) EnumDescriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{1}
}

type UploadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Chunk         []byte                 `protobuf:"bytes,1,opt,name=chunk,proto3" json:"chunk,omitempty"`
	RelationType  RelationType           `protobuf:"varint,2,opt,name=relation_type,json=relationType,proto3,enum=proto.RelationType" json:"relation_type,omitempty"`
	RelationId    string                 `protobuf:"bytes,3,opt,name=relation_id,json=relationId,proto3" json:"relation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadRequest) Reset() {
	*x = UploadRequest{}
	mi := &file_media_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadRequest) ProtoMessage() {}

func (x *UploadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadRequest.ProtoReflect.Descriptor instead.
func (*UploadRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{0}
}

func (x *UploadRequest) GetChunk() []byte {
	if x != nil {
		return x.Chunk
	}
	return nil
}

func (x *UploadRequest) GetRelationType() RelationType {
	if x != nil {
		return x.RelationType
	}
	return RelationType_MEDIA_TYPE_UNSPECIFIED
}

func (x *UploadRequest) GetRelationId() string {
	if x != nil {
		return x.RelationId
	}
	return ""
}

type UploadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UploadResponse) Reset() {
	*x = UploadResponse{}
	mi := &file_media_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UploadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UploadResponse) ProtoMessage() {}

func (x *UploadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UploadResponse.ProtoReflect.Descriptor instead.
func (*UploadResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{1}
}

func (x *UploadResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ConfirmRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmRequest) Reset() {
	*x = ConfirmRequest{}
	mi := &file_media_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmRequest) ProtoMessage() {}

func (x *ConfirmRequest) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmRequest.ProtoReflect.Descriptor instead.
func (*ConfirmRequest) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{2}
}

func (x *ConfirmRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type ConfirmResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ConfirmResponse) Reset() {
	*x = ConfirmResponse{}
	mi := &file_media_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConfirmResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConfirmResponse) ProtoMessage() {}

func (x *ConfirmResponse) ProtoReflect() protoreflect.Message {
	mi := &file_media_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConfirmResponse.ProtoReflect.Descriptor instead.
func (*ConfirmResponse) Descriptor() ([]byte, []int) {
	return file_media_proto_rawDescGZIP(), []int{3}
}

func (x *ConfirmResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_media_proto protoreflect.FileDescriptor

const file_media_proto_rawDesc = "" +
	"\n" +
	"\vmedia.proto\x12\x05proto\x1a\x1cgoogle/api/annotations.proto\"\x80\x01\n" +
	"\rUploadRequest\x12\x14\n" +
	"\x05chunk\x18\x01 \x01(\fR\x05chunk\x128\n" +
	"\rrelation_type\x18\x02 \x01(\x0e2\x13.proto.RelationTypeR\frelationType\x12\x1f\n" +
	"\vrelation_id\x18\x03 \x01(\tR\n" +
	"relationId\" \n" +
	"\x0eUploadResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\" \n" +
	"\x0eConfirmRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"+\n" +
	"\x0fConfirmResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage*\x83\x02\n" +
	"\fRelationType\x12\x1a\n" +
	"\x16MEDIA_TYPE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16MEDIA_TYPE_USER_AVATAR\x10\x01\x12\x1a\n" +
	"\x16MEDIA_TYPE_USER_BANNER\x10\x02\x12!\n" +
	"\x1dMEDIA_TYPE_COMMENT_ATTACHMENT\x10\x03\x12\x1c\n" +
	"\x18MEDIA_TYPE_PLATFORM_LOGO\x10\x04\x12\x1e\n" +
	"\x1aMEDIA_TYPE_PLATFORM_BANNER\x10\x05\x12\x1d\n" +
	"\x19MEDIA_TYPE_COMMUNITY_LOGO\x10\x06\x12\x1f\n" +
	"\x1bMEDIA_TYPE_COMMUNITY_BANNER\x10\a*w\n" +
	"\bFileType\x12\x19\n" +
	"\x15FILE_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fFILE_TYPE_IMAGE\x10\x01\x12\x13\n" +
	"\x0fFILE_TYPE_VIDEO\x10\x02\x12\x13\n" +
	"\x0fFILE_TYPE_AUDIO\x10\x03\x12\x11\n" +
	"\rFILE_TYPE_GIF\x10\x042\xb4\x01\n" +
	"\fMediaService\x12O\n" +
	"\x06Upload\x12\x14.proto.UploadRequest\x1a\x15.proto.UploadResponse\"\x18\x82\xd3\xe4\x93\x02\x12:\x01*\"\r/media/upload\x12S\n" +
	"\aConfirm\x12\x15.proto.ConfirmRequest\x1a\x16.proto.ConfirmResponse\"\x19\x82\xd3\xe4\x93\x02\x13:\x01*\"\x0e/media/confirmB\bZ\x06/protob\x06proto3"

var (
	file_media_proto_rawDescOnce sync.Once
	file_media_proto_rawDescData []byte
)

func file_media_proto_rawDescGZIP() []byte {
	file_media_proto_rawDescOnce.Do(func() {
		file_media_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_media_proto_rawDesc), len(file_media_proto_rawDesc)))
	})
	return file_media_proto_rawDescData
}

var file_media_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_media_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_media_proto_goTypes = []any{
	(RelationType)(0),       // 0: proto.RelationType
	(FileType)(0),           // 1: proto.FileType
	(*UploadRequest)(nil),   // 2: proto.UploadRequest
	(*UploadResponse)(nil),  // 3: proto.UploadResponse
	(*ConfirmRequest)(nil),  // 4: proto.ConfirmRequest
	(*ConfirmResponse)(nil), // 5: proto.ConfirmResponse
}
var file_media_proto_depIdxs = []int32{
	0, // 0: proto.UploadRequest.relation_type:type_name -> proto.RelationType
	2, // 1: proto.MediaService.Upload:input_type -> proto.UploadRequest
	4, // 2: proto.MediaService.Confirm:input_type -> proto.ConfirmRequest
	3, // 3: proto.MediaService.Upload:output_type -> proto.UploadResponse
	5, // 4: proto.MediaService.Confirm:output_type -> proto.ConfirmResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_media_proto_init() }
func file_media_proto_init() {
	if File_media_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_media_proto_rawDesc), len(file_media_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_media_proto_goTypes,
		DependencyIndexes: file_media_proto_depIdxs,
		EnumInfos:         file_media_proto_enumTypes,
		MessageInfos:      file_media_proto_msgTypes,
	}.Build()
	File_media_proto = out.File
	file_media_proto_goTypes = nil
	file_media_proto_depIdxs = nil
}
