// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: notification.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type NotificationType int32

const (
	NotificationType_NOTIFICATION_TYPE_UNSPECIFIED                 NotificationType = 0
	NotificationType_NOTIFICATION_TYPE_NEW_POST_IN_COMMUNITY       NotificationType = 1
	NotificationType_NOTIFICATION_TYPE_NEW_POST_FROM_FOLLOWED_USER NotificationType = 2
	NotificationType_NOTIFICATION_TYPE_COMMENT_LIKED               NotificationType = 3
	NotificationType_NOTIFICATION_TYPE_NEW_COMMENT_IN_POST         NotificationType = 4
	NotificationType_NOTIFICATION_TYPE_COMMENT_REPLY               NotificationType = 5
)

// Enum value maps for NotificationType.
var (
	NotificationType_name = map[int32]string{
		0: "NOTIFICATION_TYPE_UNSPECIFIED",
		1: "NOTIFICATION_TYPE_NEW_POST_IN_COMMUNITY",
		2: "NOTIFICATION_TYPE_NEW_POST_FROM_FOLLOWED_USER",
		3: "NOTIFICATION_TYPE_COMMENT_LIKED",
		4: "NOTIFICATION_TYPE_NEW_COMMENT_IN_POST",
		5: "NOTIFICATION_TYPE_COMMENT_REPLY",
	}
	NotificationType_value = map[string]int32{
		"NOTIFICATION_TYPE_UNSPECIFIED":                 0,
		"NOTIFICATION_TYPE_NEW_POST_IN_COMMUNITY":       1,
		"NOTIFICATION_TYPE_NEW_POST_FROM_FOLLOWED_USER": 2,
		"NOTIFICATION_TYPE_COMMENT_LIKED":               3,
		"NOTIFICATION_TYPE_NEW_COMMENT_IN_POST":         4,
		"NOTIFICATION_TYPE_COMMENT_REPLY":               5,
	}
)

func (x NotificationType) Enum() *NotificationType {
	p := new(NotificationType)
	*p = x
	return p
}

func (x NotificationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (NotificationType) Descriptor() protoreflect.EnumDescriptor {
	return file_notification_proto_enumTypes[0].Descriptor()
}

func (NotificationType) Type() protoreflect.EnumType {
	return &file_notification_proto_enumTypes[0]
}

func (x NotificationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use NotificationType.Descriptor instead.
func (NotificationType) EnumDescriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{0}
}

// Notification content structure (FR-418, FR-433-438)
type NotificationContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ActorUsername string                 `protobuf:"bytes,1,opt,name=actor_username,json=actorUsername,proto3" json:"actor_username,omitempty"`
	ActorAvatar   string                 `protobuf:"bytes,2,opt,name=actor_avatar,json=actorAvatar,proto3" json:"actor_avatar,omitempty"`
	TargetType    string                 `protobuf:"bytes,3,opt,name=target_type,json=targetType,proto3" json:"target_type,omitempty"` // post or comment
	TargetId      string                 `protobuf:"bytes,4,opt,name=target_id,json=targetId,proto3" json:"target_id,omitempty"`
	ActionType    string                 `protobuf:"bytes,5,opt,name=action_type,json=actionType,proto3" json:"action_type,omitempty"`
	// Type-specific fields
	CommunityName     *string                `protobuf:"bytes,6,opt,name=community_name,json=communityName,proto3,oneof" json:"community_name,omitempty"`
	PostTitle         *string                `protobuf:"bytes,7,opt,name=post_title,json=postTitle,proto3,oneof" json:"post_title,omitempty"`
	PostId            *string                `protobuf:"bytes,8,opt,name=post_id,json=postId,proto3,oneof" json:"post_id,omitempty"`
	CommentId         *string                `protobuf:"bytes,9,opt,name=comment_id,json=commentId,proto3,oneof" json:"comment_id,omitempty"`
	CommentText       *string                `protobuf:"bytes,10,opt,name=comment_text,json=commentText,proto3,oneof" json:"comment_text,omitempty"` // truncated to 100 chars
	OriginalCommentId *string                `protobuf:"bytes,11,opt,name=original_comment_id,json=originalCommentId,proto3,oneof" json:"original_comment_id,omitempty"`
	ReplyText         *string                `protobuf:"bytes,12,opt,name=reply_text,json=replyText,proto3,oneof" json:"reply_text,omitempty"`
	Timestamp         *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *NotificationContent) Reset() {
	*x = NotificationContent{}
	mi := &file_notification_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationContent) ProtoMessage() {}

func (x *NotificationContent) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationContent.ProtoReflect.Descriptor instead.
func (*NotificationContent) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{0}
}

func (x *NotificationContent) GetActorUsername() string {
	if x != nil {
		return x.ActorUsername
	}
	return ""
}

func (x *NotificationContent) GetActorAvatar() string {
	if x != nil {
		return x.ActorAvatar
	}
	return ""
}

func (x *NotificationContent) GetTargetType() string {
	if x != nil {
		return x.TargetType
	}
	return ""
}

func (x *NotificationContent) GetTargetId() string {
	if x != nil {
		return x.TargetId
	}
	return ""
}

func (x *NotificationContent) GetActionType() string {
	if x != nil {
		return x.ActionType
	}
	return ""
}

func (x *NotificationContent) GetCommunityName() string {
	if x != nil && x.CommunityName != nil {
		return *x.CommunityName
	}
	return ""
}

func (x *NotificationContent) GetPostTitle() string {
	if x != nil && x.PostTitle != nil {
		return *x.PostTitle
	}
	return ""
}

func (x *NotificationContent) GetPostId() string {
	if x != nil && x.PostId != nil {
		return *x.PostId
	}
	return ""
}

func (x *NotificationContent) GetCommentId() string {
	if x != nil && x.CommentId != nil {
		return *x.CommentId
	}
	return ""
}

func (x *NotificationContent) GetCommentText() string {
	if x != nil && x.CommentText != nil {
		return *x.CommentText
	}
	return ""
}

func (x *NotificationContent) GetOriginalCommentId() string {
	if x != nil && x.OriginalCommentId != nil {
		return *x.OriginalCommentId
	}
	return ""
}

func (x *NotificationContent) GetReplyText() string {
	if x != nil && x.ReplyText != nil {
		return *x.ReplyText
	}
	return ""
}

func (x *NotificationContent) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

type Notification struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	UserId        string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Type          NotificationType       `protobuf:"varint,3,opt,name=type,proto3,enum=proto.NotificationType" json:"type,omitempty"`
	Content       *NotificationContent   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	IsRead        bool                   `protobuf:"varint,5,opt,name=is_read,json=isRead,proto3" json:"is_read,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Notification) Reset() {
	*x = Notification{}
	mi := &file_notification_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Notification) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Notification) ProtoMessage() {}

func (x *Notification) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Notification.ProtoReflect.Descriptor instead.
func (*Notification) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{1}
}

func (x *Notification) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Notification) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *Notification) GetType() NotificationType {
	if x != nil {
		return x.Type
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *Notification) GetContent() *NotificationContent {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Notification) GetIsRead() bool {
	if x != nil {
		return x.IsRead
	}
	return false
}

func (x *Notification) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type NotificationPreferences struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	NewPostInCommunity      bool                   `protobuf:"varint,1,opt,name=new_post_in_community,json=newPostInCommunity,proto3" json:"new_post_in_community,omitempty"`
	NewPostFromFollowedUser bool                   `protobuf:"varint,2,opt,name=new_post_from_followed_user,json=newPostFromFollowedUser,proto3" json:"new_post_from_followed_user,omitempty"`
	CommentLiked            bool                   `protobuf:"varint,3,opt,name=comment_liked,json=commentLiked,proto3" json:"comment_liked,omitempty"`
	NewCommentInPost        bool                   `protobuf:"varint,4,opt,name=new_comment_in_post,json=newCommentInPost,proto3" json:"new_comment_in_post,omitempty"`
	CommentReply            bool                   `protobuf:"varint,5,opt,name=comment_reply,json=commentReply,proto3" json:"comment_reply,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *NotificationPreferences) Reset() {
	*x = NotificationPreferences{}
	mi := &file_notification_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotificationPreferences) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotificationPreferences) ProtoMessage() {}

func (x *NotificationPreferences) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotificationPreferences.ProtoReflect.Descriptor instead.
func (*NotificationPreferences) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{2}
}

func (x *NotificationPreferences) GetNewPostInCommunity() bool {
	if x != nil {
		return x.NewPostInCommunity
	}
	return false
}

func (x *NotificationPreferences) GetNewPostFromFollowedUser() bool {
	if x != nil {
		return x.NewPostFromFollowedUser
	}
	return false
}

func (x *NotificationPreferences) GetCommentLiked() bool {
	if x != nil {
		return x.CommentLiked
	}
	return false
}

func (x *NotificationPreferences) GetNewCommentInPost() bool {
	if x != nil {
		return x.NewCommentInPost
	}
	return false
}

func (x *NotificationPreferences) GetCommentReply() bool {
	if x != nil {
		return x.CommentReply
	}
	return false
}

type StreamNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StreamNotificationRequest) Reset() {
	*x = StreamNotificationRequest{}
	mi := &file_notification_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StreamNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StreamNotificationRequest) ProtoMessage() {}

func (x *StreamNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StreamNotificationRequest.ProtoReflect.Descriptor instead.
func (*StreamNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{3}
}

type GetNotificationRequest struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ReadStatusFilter *bool                  `protobuf:"varint,1,opt,name=read_status_filter,json=readStatusFilter,proto3,oneof" json:"read_status_filter,omitempty"` // if set, filter by read status
	TypeFilter       *NotificationType      `protobuf:"varint,2,opt,name=type_filter,json=typeFilter,proto3,enum=proto.NotificationType,oneof" json:"type_filter,omitempty"`
	Cursor           string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit            int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *GetNotificationRequest) Reset() {
	*x = GetNotificationRequest{}
	mi := &file_notification_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationRequest) ProtoMessage() {}

func (x *GetNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationRequest.ProtoReflect.Descriptor instead.
func (*GetNotificationRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{4}
}

func (x *GetNotificationRequest) GetReadStatusFilter() bool {
	if x != nil && x.ReadStatusFilter != nil {
		return *x.ReadStatusFilter
	}
	return false
}

func (x *GetNotificationRequest) GetTypeFilter() NotificationType {
	if x != nil && x.TypeFilter != nil {
		return *x.TypeFilter
	}
	return NotificationType_NOTIFICATION_TYPE_UNSPECIFIED
}

func (x *GetNotificationRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *GetNotificationRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type GetNotificationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Notifications []*Notification        `protobuf:"bytes,1,rep,name=notifications,proto3" json:"notifications,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetNotificationResponse) Reset() {
	*x = GetNotificationResponse{}
	mi := &file_notification_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetNotificationResponse) ProtoMessage() {}

func (x *GetNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetNotificationResponse.ProtoReflect.Descriptor instead.
func (*GetNotificationResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{5}
}

func (x *GetNotificationResponse) GetNotifications() []*Notification {
	if x != nil {
		return x.Notifications
	}
	return nil
}

func (x *GetNotificationResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *GetNotificationResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type MarkAsReadRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	NotificationId string                 `protobuf:"bytes,1,opt,name=notification_id,json=notificationId,proto3" json:"notification_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MarkAsReadRequest) Reset() {
	*x = MarkAsReadRequest{}
	mi := &file_notification_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsReadRequest) ProtoMessage() {}

func (x *MarkAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAsReadRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{6}
}

func (x *MarkAsReadRequest) GetNotificationId() string {
	if x != nil {
		return x.NotificationId
	}
	return ""
}

type MarkAsReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAsReadResponse) Reset() {
	*x = MarkAsReadResponse{}
	mi := &file_notification_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAsReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAsReadResponse) ProtoMessage() {}

func (x *MarkAsReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAsReadResponse.ProtoReflect.Descriptor instead.
func (*MarkAsReadResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{7}
}

func (x *MarkAsReadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type MarkAllAsReadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllAsReadRequest) Reset() {
	*x = MarkAllAsReadRequest{}
	mi := &file_notification_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllAsReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllAsReadRequest) ProtoMessage() {}

func (x *MarkAllAsReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllAsReadRequest.ProtoReflect.Descriptor instead.
func (*MarkAllAsReadRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{8}
}

type MarkAllAsReadResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	MarkedCount   int32                  `protobuf:"varint,2,opt,name=marked_count,json=markedCount,proto3" json:"marked_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MarkAllAsReadResponse) Reset() {
	*x = MarkAllAsReadResponse{}
	mi := &file_notification_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MarkAllAsReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MarkAllAsReadResponse) ProtoMessage() {}

func (x *MarkAllAsReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MarkAllAsReadResponse.ProtoReflect.Descriptor instead.
func (*MarkAllAsReadResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{9}
}

func (x *MarkAllAsReadResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *MarkAllAsReadResponse) GetMarkedCount() int32 {
	if x != nil {
		return x.MarkedCount
	}
	return 0
}

type GetUnreadCountRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountRequest) Reset() {
	*x = GetUnreadCountRequest{}
	mi := &file_notification_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountRequest) ProtoMessage() {}

func (x *GetUnreadCountRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountRequest.ProtoReflect.Descriptor instead.
func (*GetUnreadCountRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{10}
}

type GetUnreadCountResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UnreadCount   int32                  `protobuf:"varint,1,opt,name=unread_count,json=unreadCount,proto3" json:"unread_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUnreadCountResponse) Reset() {
	*x = GetUnreadCountResponse{}
	mi := &file_notification_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUnreadCountResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUnreadCountResponse) ProtoMessage() {}

func (x *GetUnreadCountResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUnreadCountResponse.ProtoReflect.Descriptor instead.
func (*GetUnreadCountResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{11}
}

func (x *GetUnreadCountResponse) GetUnreadCount() int32 {
	if x != nil {
		return x.UnreadCount
	}
	return 0
}

type GetPreferencesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreferencesRequest) Reset() {
	*x = GetPreferencesRequest{}
	mi := &file_notification_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreferencesRequest) ProtoMessage() {}

func (x *GetPreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreferencesRequest.ProtoReflect.Descriptor instead.
func (*GetPreferencesRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{12}
}

type GetPreferencesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Preferences   *NotificationPreferences `protobuf:"bytes,1,opt,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPreferencesResponse) Reset() {
	*x = GetPreferencesResponse{}
	mi := &file_notification_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPreferencesResponse) ProtoMessage() {}

func (x *GetPreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPreferencesResponse.ProtoReflect.Descriptor instead.
func (*GetPreferencesResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{13}
}

func (x *GetPreferencesResponse) GetPreferences() *NotificationPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

type UpdatePreferencesRequest struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Preferences   *NotificationPreferences `protobuf:"bytes,1,opt,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePreferencesRequest) Reset() {
	*x = UpdatePreferencesRequest{}
	mi := &file_notification_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePreferencesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferencesRequest) ProtoMessage() {}

func (x *UpdatePreferencesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreferencesRequest.ProtoReflect.Descriptor instead.
func (*UpdatePreferencesRequest) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{14}
}

func (x *UpdatePreferencesRequest) GetPreferences() *NotificationPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

type UpdatePreferencesResponse struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Preferences   *NotificationPreferences `protobuf:"bytes,1,opt,name=preferences,proto3" json:"preferences,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdatePreferencesResponse) Reset() {
	*x = UpdatePreferencesResponse{}
	mi := &file_notification_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdatePreferencesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdatePreferencesResponse) ProtoMessage() {}

func (x *UpdatePreferencesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_notification_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdatePreferencesResponse.ProtoReflect.Descriptor instead.
func (*UpdatePreferencesResponse) Descriptor() ([]byte, []int) {
	return file_notification_proto_rawDescGZIP(), []int{15}
}

func (x *UpdatePreferencesResponse) GetPreferences() *NotificationPreferences {
	if x != nil {
		return x.Preferences
	}
	return nil
}

var File_notification_proto protoreflect.FileDescriptor

const file_notification_proto_rawDesc = "" +
	"\n" +
	"\x12notification.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\x80\x05\n" +
	"\x13NotificationContent\x12%\n" +
	"\x0eactor_username\x18\x01 \x01(\tR\ractorUsername\x12!\n" +
	"\factor_avatar\x18\x02 \x01(\tR\vactorAvatar\x12\x1f\n" +
	"\vtarget_type\x18\x03 \x01(\tR\n" +
	"targetType\x12\x1b\n" +
	"\ttarget_id\x18\x04 \x01(\tR\btargetId\x12\x1f\n" +
	"\vaction_type\x18\x05 \x01(\tR\n" +
	"actionType\x12*\n" +
	"\x0ecommunity_name\x18\x06 \x01(\tH\x00R\rcommunityName\x88\x01\x01\x12\"\n" +
	"\n" +
	"post_title\x18\a \x01(\tH\x01R\tpostTitle\x88\x01\x01\x12\x1c\n" +
	"\apost_id\x18\b \x01(\tH\x02R\x06postId\x88\x01\x01\x12\"\n" +
	"\n" +
	"comment_id\x18\t \x01(\tH\x03R\tcommentId\x88\x01\x01\x12&\n" +
	"\fcomment_text\x18\n" +
	" \x01(\tH\x04R\vcommentText\x88\x01\x01\x123\n" +
	"\x13original_comment_id\x18\v \x01(\tH\x05R\x11originalCommentId\x88\x01\x01\x12\"\n" +
	"\n" +
	"reply_text\x18\f \x01(\tH\x06R\treplyText\x88\x01\x01\x128\n" +
	"\ttimestamp\x18\r \x01(\v2\x1a.google.protobuf.TimestampR\ttimestampB\x11\n" +
	"\x0f_community_nameB\r\n" +
	"\v_post_titleB\n" +
	"\n" +
	"\b_post_idB\r\n" +
	"\v_comment_idB\x0f\n" +
	"\r_comment_textB\x16\n" +
	"\x14_original_comment_idB\r\n" +
	"\v_reply_text\"\xee\x01\n" +
	"\fNotification\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12+\n" +
	"\x04type\x18\x03 \x01(\x0e2\x17.proto.NotificationTypeR\x04type\x124\n" +
	"\acontent\x18\x04 \x01(\v2\x1a.proto.NotificationContentR\acontent\x12\x17\n" +
	"\ais_read\x18\x05 \x01(\bR\x06isRead\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\x83\x02\n" +
	"\x17NotificationPreferences\x121\n" +
	"\x15new_post_in_community\x18\x01 \x01(\bR\x12newPostInCommunity\x12<\n" +
	"\x1bnew_post_from_followed_user\x18\x02 \x01(\bR\x17newPostFromFollowedUser\x12#\n" +
	"\rcomment_liked\x18\x03 \x01(\bR\fcommentLiked\x12-\n" +
	"\x13new_comment_in_post\x18\x04 \x01(\bR\x10newCommentInPost\x12#\n" +
	"\rcomment_reply\x18\x05 \x01(\bR\fcommentReply\"\x1b\n" +
	"\x19StreamNotificationRequest\"\xdf\x01\n" +
	"\x16GetNotificationRequest\x121\n" +
	"\x12read_status_filter\x18\x01 \x01(\bH\x00R\x10readStatusFilter\x88\x01\x01\x12=\n" +
	"\vtype_filter\x18\x02 \x01(\x0e2\x17.proto.NotificationTypeH\x01R\n" +
	"typeFilter\x88\x01\x01\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limitB\x15\n" +
	"\x13_read_status_filterB\x0e\n" +
	"\f_type_filter\"\x90\x01\n" +
	"\x17GetNotificationResponse\x129\n" +
	"\rnotifications\x18\x01 \x03(\v2\x13.proto.NotificationR\rnotifications\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"<\n" +
	"\x11MarkAsReadRequest\x12'\n" +
	"\x0fnotification_id\x18\x01 \x01(\tR\x0enotificationId\".\n" +
	"\x12MarkAsReadResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\"\x16\n" +
	"\x14MarkAllAsReadRequest\"T\n" +
	"\x15MarkAllAsReadResponse\x12\x18\n" +
	"\amessage\x18\x01 \x01(\tR\amessage\x12!\n" +
	"\fmarked_count\x18\x02 \x01(\x05R\vmarkedCount\"\x17\n" +
	"\x15GetUnreadCountRequest\";\n" +
	"\x16GetUnreadCountResponse\x12!\n" +
	"\funread_count\x18\x01 \x01(\x05R\vunreadCount\"\x17\n" +
	"\x15GetPreferencesRequest\"Z\n" +
	"\x16GetPreferencesResponse\x12@\n" +
	"\vpreferences\x18\x01 \x01(\v2\x1e.proto.NotificationPreferencesR\vpreferences\"\\\n" +
	"\x18UpdatePreferencesRequest\x12@\n" +
	"\vpreferences\x18\x01 \x01(\v2\x1e.proto.NotificationPreferencesR\vpreferences\"]\n" +
	"\x19UpdatePreferencesResponse\x12@\n" +
	"\vpreferences\x18\x01 \x01(\v2\x1e.proto.NotificationPreferencesR\vpreferences*\x8a\x02\n" +
	"\x10NotificationType\x12!\n" +
	"\x1dNOTIFICATION_TYPE_UNSPECIFIED\x10\x00\x12+\n" +
	"'NOTIFICATION_TYPE_NEW_POST_IN_COMMUNITY\x10\x01\x121\n" +
	"-NOTIFICATION_TYPE_NEW_POST_FROM_FOLLOWED_USER\x10\x02\x12#\n" +
	"\x1fNOTIFICATION_TYPE_COMMENT_LIKED\x10\x03\x12)\n" +
	"%NOTIFICATION_TYPE_NEW_COMMENT_IN_POST\x10\x04\x12#\n" +
	"\x1fNOTIFICATION_TYPE_COMMENT_REPLY\x10\x052\xfd\x05\n" +
	"\x13NotificationService\x12C\n" +
	"\x06Stream\x12 .proto.StreamNotificationRequest\x1a\x13.proto.Notification\"\x000\x01\x12\\\n" +
	"\x03Get\x12\x1d.proto.GetNotificationRequest\x1a\x1e.proto.GetNotificationResponse\"\x16\x82\xd3\xe4\x93\x02\x10\x12\x0e/notifications\x12p\n" +
	"\n" +
	"MarkAsRead\x12\x18.proto.MarkAsReadRequest\x1a\x19.proto.MarkAsReadResponse\"-\x82\xd3\xe4\x93\x02'\"%/notifications/{notification_id}/read\x12k\n" +
	"\rMarkAllAsRead\x12\x1b.proto.MarkAllAsReadRequest\x1a\x1c.proto.MarkAllAsReadResponse\"\x1f\x82\xd3\xe4\x93\x02\x19\"\x17/notifications/read-all\x12r\n" +
	"\x0eGetUnreadCount\x12\x1c.proto.GetUnreadCountRequest\x1a\x1d.proto.GetUnreadCountResponse\"#\x82\xd3\xe4\x93\x02\x1d\x12\x1b/notifications/unread-count\x12q\n" +
	"\x0eGetPreferences\x12\x1c.proto.GetPreferencesRequest\x1a\x1d.proto.GetPreferencesResponse\"\"\x82\xd3\xe4\x93\x02\x1c\x12\x1a/notifications/preferences\x12}\n" +
	"\x11UpdatePreferences\x12\x1f.proto.UpdatePreferencesRequest\x1a .proto.UpdatePreferencesResponse\"%\x82\xd3\xe4\x93\x02\x1f:\x01*\x1a\x1a/notifications/preferencesB\bZ\x06/protob\x06proto3"

var (
	file_notification_proto_rawDescOnce sync.Once
	file_notification_proto_rawDescData []byte
)

func file_notification_proto_rawDescGZIP() []byte {
	file_notification_proto_rawDescOnce.Do(func() {
		file_notification_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)))
	})
	return file_notification_proto_rawDescData
}

var file_notification_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_notification_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_notification_proto_goTypes = []any{
	(NotificationType)(0),             // 0: proto.NotificationType
	(*NotificationContent)(nil),       // 1: proto.NotificationContent
	(*Notification)(nil),              // 2: proto.Notification
	(*NotificationPreferences)(nil),   // 3: proto.NotificationPreferences
	(*StreamNotificationRequest)(nil), // 4: proto.StreamNotificationRequest
	(*GetNotificationRequest)(nil),    // 5: proto.GetNotificationRequest
	(*GetNotificationResponse)(nil),   // 6: proto.GetNotificationResponse
	(*MarkAsReadRequest)(nil),         // 7: proto.MarkAsReadRequest
	(*MarkAsReadResponse)(nil),        // 8: proto.MarkAsReadResponse
	(*MarkAllAsReadRequest)(nil),      // 9: proto.MarkAllAsReadRequest
	(*MarkAllAsReadResponse)(nil),     // 10: proto.MarkAllAsReadResponse
	(*GetUnreadCountRequest)(nil),     // 11: proto.GetUnreadCountRequest
	(*GetUnreadCountResponse)(nil),    // 12: proto.GetUnreadCountResponse
	(*GetPreferencesRequest)(nil),     // 13: proto.GetPreferencesRequest
	(*GetPreferencesResponse)(nil),    // 14: proto.GetPreferencesResponse
	(*UpdatePreferencesRequest)(nil),  // 15: proto.UpdatePreferencesRequest
	(*UpdatePreferencesResponse)(nil), // 16: proto.UpdatePreferencesResponse
	(*timestamppb.Timestamp)(nil),     // 17: google.protobuf.Timestamp
}
var file_notification_proto_depIdxs = []int32{
	17, // 0: proto.NotificationContent.timestamp:type_name -> google.protobuf.Timestamp
	0,  // 1: proto.Notification.type:type_name -> proto.NotificationType
	1,  // 2: proto.Notification.content:type_name -> proto.NotificationContent
	17, // 3: proto.Notification.created_at:type_name -> google.protobuf.Timestamp
	0,  // 4: proto.GetNotificationRequest.type_filter:type_name -> proto.NotificationType
	2,  // 5: proto.GetNotificationResponse.notifications:type_name -> proto.Notification
	3,  // 6: proto.GetPreferencesResponse.preferences:type_name -> proto.NotificationPreferences
	3,  // 7: proto.UpdatePreferencesRequest.preferences:type_name -> proto.NotificationPreferences
	3,  // 8: proto.UpdatePreferencesResponse.preferences:type_name -> proto.NotificationPreferences
	4,  // 9: proto.NotificationService.Stream:input_type -> proto.StreamNotificationRequest
	5,  // 10: proto.NotificationService.Get:input_type -> proto.GetNotificationRequest
	7,  // 11: proto.NotificationService.MarkAsRead:input_type -> proto.MarkAsReadRequest
	9,  // 12: proto.NotificationService.MarkAllAsRead:input_type -> proto.MarkAllAsReadRequest
	11, // 13: proto.NotificationService.GetUnreadCount:input_type -> proto.GetUnreadCountRequest
	13, // 14: proto.NotificationService.GetPreferences:input_type -> proto.GetPreferencesRequest
	15, // 15: proto.NotificationService.UpdatePreferences:input_type -> proto.UpdatePreferencesRequest
	2,  // 16: proto.NotificationService.Stream:output_type -> proto.Notification
	6,  // 17: proto.NotificationService.Get:output_type -> proto.GetNotificationResponse
	8,  // 18: proto.NotificationService.MarkAsRead:output_type -> proto.MarkAsReadResponse
	10, // 19: proto.NotificationService.MarkAllAsRead:output_type -> proto.MarkAllAsReadResponse
	12, // 20: proto.NotificationService.GetUnreadCount:output_type -> proto.GetUnreadCountResponse
	14, // 21: proto.NotificationService.GetPreferences:output_type -> proto.GetPreferencesResponse
	16, // 22: proto.NotificationService.UpdatePreferences:output_type -> proto.UpdatePreferencesResponse
	16, // [16:23] is the sub-list for method output_type
	9,  // [9:16] is the sub-list for method input_type
	9,  // [9:9] is the sub-list for extension type_name
	9,  // [9:9] is the sub-list for extension extendee
	0,  // [0:9] is the sub-list for field type_name
}

func init() { file_notification_proto_init() }
func file_notification_proto_init() {
	if File_notification_proto != nil {
		return
	}
	file_notification_proto_msgTypes[0].OneofWrappers = []any{}
	file_notification_proto_msgTypes[4].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_notification_proto_rawDesc), len(file_notification_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_notification_proto_goTypes,
		DependencyIndexes: file_notification_proto_depIdxs,
		EnumInfos:         file_notification_proto_enumTypes,
		MessageInfos:      file_notification_proto_msgTypes,
	}.Build()
	File_notification_proto = out.File
	file_notification_proto_goTypes = nil
	file_notification_proto_depIdxs = nil
}
