// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: report.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReportReason int32

const (
	ReportReason_REPORT_REASON_UNSPECIFIED      ReportReason = 0
	ReportReason_REPORT_REASON_SPAM             ReportReason = 1
	ReportReason_REPORT_REASON_HARASSMENT       ReportReason = 2
	ReportReason_REPORT_REASON_MISINFORMATION   ReportReason = 3
	ReportReason_REPORT_REASON_EXPLICIT_CONTENT ReportReason = 4
	ReportReason_REPORT_REASON_VIOLENCE         ReportReason = 5
	ReportReason_REPORT_REASON_HATE_SPEECH      ReportReason = 6
	ReportReason_REPORT_REASON_OTHER            ReportReason = 7
)

// Enum value maps for ReportReason.
var (
	ReportReason_name = map[int32]string{
		0: "REPORT_REASON_UNSPECIFIED",
		1: "REPORT_REASON_SPAM",
		2: "REPORT_REASON_HARASSMENT",
		3: "REPORT_REASON_MISINFORMATION",
		4: "REPORT_REASON_EXPLICIT_CONTENT",
		5: "REPORT_REASON_VIOLENCE",
		6: "REPORT_REASON_HATE_SPEECH",
		7: "REPORT_REASON_OTHER",
	}
	ReportReason_value = map[string]int32{
		"REPORT_REASON_UNSPECIFIED":      0,
		"REPORT_REASON_SPAM":             1,
		"REPORT_REASON_HARASSMENT":       2,
		"REPORT_REASON_MISINFORMATION":   3,
		"REPORT_REASON_EXPLICIT_CONTENT": 4,
		"REPORT_REASON_VIOLENCE":         5,
		"REPORT_REASON_HATE_SPEECH":      6,
		"REPORT_REASON_OTHER":            7,
	}
)

func (x ReportReason) Enum() *ReportReason {
	p := new(ReportReason)
	*p = x
	return p
}

func (x ReportReason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReportReason) Descriptor() protoreflect.EnumDescriptor {
	return file_report_proto_enumTypes[0].Descriptor()
}

func (ReportReason) Type() protoreflect.EnumType {
	return &file_report_proto_enumTypes[0]
}

func (x ReportReason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReportReason.Descriptor instead.
func (ReportReason) EnumDescriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{0}
}

type ReportStatus int32

const (
	ReportStatus_REPORT_STATUS_UNSPECIFIED ReportStatus = 0
	ReportStatus_REPORT_STATUS_PENDING     ReportStatus = 1
	ReportStatus_REPORT_STATUS_RESOLVED    ReportStatus = 2
	ReportStatus_REPORT_STATUS_DISMISSED   ReportStatus = 3
)

// Enum value maps for ReportStatus.
var (
	ReportStatus_name = map[int32]string{
		0: "REPORT_STATUS_UNSPECIFIED",
		1: "REPORT_STATUS_PENDING",
		2: "REPORT_STATUS_RESOLVED",
		3: "REPORT_STATUS_DISMISSED",
	}
	ReportStatus_value = map[string]int32{
		"REPORT_STATUS_UNSPECIFIED": 0,
		"REPORT_STATUS_PENDING":     1,
		"REPORT_STATUS_RESOLVED":    2,
		"REPORT_STATUS_DISMISSED":   3,
	}
)

func (x ReportStatus) Enum() *ReportStatus {
	p := new(ReportStatus)
	*p = x
	return p
}

func (x ReportStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReportStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_report_proto_enumTypes[1].Descriptor()
}

func (ReportStatus) Type() protoreflect.EnumType {
	return &file_report_proto_enumTypes[1]
}

func (x ReportStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReportStatus.Descriptor instead.
func (ReportStatus) EnumDescriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{1}
}

type ReportedContentType int32

const (
	ReportedContentType_REPORTED_CONTENT_TYPE_UNSPECIFIED ReportedContentType = 0
	ReportedContentType_REPORTED_CONTENT_TYPE_POST        ReportedContentType = 1
	ReportedContentType_REPORTED_CONTENT_TYPE_COMMENT     ReportedContentType = 2
)

// Enum value maps for ReportedContentType.
var (
	ReportedContentType_name = map[int32]string{
		0: "REPORTED_CONTENT_TYPE_UNSPECIFIED",
		1: "REPORTED_CONTENT_TYPE_POST",
		2: "REPORTED_CONTENT_TYPE_COMMENT",
	}
	ReportedContentType_value = map[string]int32{
		"REPORTED_CONTENT_TYPE_UNSPECIFIED": 0,
		"REPORTED_CONTENT_TYPE_POST":        1,
		"REPORTED_CONTENT_TYPE_COMMENT":     2,
	}
)

func (x ReportedContentType) Enum() *ReportedContentType {
	p := new(ReportedContentType)
	*p = x
	return p
}

func (x ReportedContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ReportedContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_report_proto_enumTypes[2].Descriptor()
}

func (ReportedContentType) Type() protoreflect.EnumType {
	return &file_report_proto_enumTypes[2]
}

func (x ReportedContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ReportedContentType.Descriptor instead.
func (ReportedContentType) EnumDescriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{2}
}

type Report struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	ReporterId       string                 `protobuf:"bytes,2,opt,name=reporter_id,json=reporterId,proto3" json:"reporter_id,omitempty"`
	ReporterUsername string                 `protobuf:"bytes,3,opt,name=reporter_username,json=reporterUsername,proto3" json:"reporter_username,omitempty"`
	ContentType      ReportedContentType    `protobuf:"varint,4,opt,name=content_type,json=contentType,proto3,enum=proto.ReportedContentType" json:"content_type,omitempty"`
	ContentId        string                 `protobuf:"bytes,5,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Reason           ReportReason           `protobuf:"varint,6,opt,name=reason,proto3,enum=proto.ReportReason" json:"reason,omitempty"`
	Description      string                 `protobuf:"bytes,7,opt,name=description,proto3" json:"description,omitempty"`
	Status           ReportStatus           `protobuf:"varint,8,opt,name=status,proto3,enum=proto.ReportStatus" json:"status,omitempty"`
	ResolverId       *string                `protobuf:"bytes,9,opt,name=resolver_id,json=resolverId,proto3,oneof" json:"resolver_id,omitempty"`
	ResolverUsername *string                `protobuf:"bytes,10,opt,name=resolver_username,json=resolverUsername,proto3,oneof" json:"resolver_username,omitempty"`
	ResolutionNote   *string                `protobuf:"bytes,11,opt,name=resolution_note,json=resolutionNote,proto3,oneof" json:"resolution_note,omitempty"`
	CreatedAt        *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	ResolvedAt       *timestamppb.Timestamp `protobuf:"bytes,13,opt,name=resolved_at,json=resolvedAt,proto3,oneof" json:"resolved_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Report) Reset() {
	*x = Report{}
	mi := &file_report_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Report) ProtoMessage() {}

func (x *Report) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Report.ProtoReflect.Descriptor instead.
func (*Report) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{0}
}

func (x *Report) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Report) GetReporterId() string {
	if x != nil {
		return x.ReporterId
	}
	return ""
}

func (x *Report) GetReporterUsername() string {
	if x != nil {
		return x.ReporterUsername
	}
	return ""
}

func (x *Report) GetContentType() ReportedContentType {
	if x != nil {
		return x.ContentType
	}
	return ReportedContentType_REPORTED_CONTENT_TYPE_UNSPECIFIED
}

func (x *Report) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *Report) GetReason() ReportReason {
	if x != nil {
		return x.Reason
	}
	return ReportReason_REPORT_REASON_UNSPECIFIED
}

func (x *Report) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Report) GetStatus() ReportStatus {
	if x != nil {
		return x.Status
	}
	return ReportStatus_REPORT_STATUS_UNSPECIFIED
}

func (x *Report) GetResolverId() string {
	if x != nil && x.ResolverId != nil {
		return *x.ResolverId
	}
	return ""
}

func (x *Report) GetResolverUsername() string {
	if x != nil && x.ResolverUsername != nil {
		return *x.ResolverUsername
	}
	return ""
}

func (x *Report) GetResolutionNote() string {
	if x != nil && x.ResolutionNote != nil {
		return *x.ResolutionNote
	}
	return ""
}

func (x *Report) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Report) GetResolvedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ResolvedAt
	}
	return nil
}

type CreateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentType   ReportedContentType    `protobuf:"varint,1,opt,name=content_type,json=contentType,proto3,enum=proto.ReportedContentType" json:"content_type,omitempty"`
	ContentId     string                 `protobuf:"bytes,2,opt,name=content_id,json=contentId,proto3" json:"content_id,omitempty"`
	Reason        ReportReason           `protobuf:"varint,3,opt,name=reason,proto3,enum=proto.ReportReason" json:"reason,omitempty"`
	Description   string                 `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"` // 10-1000 chars
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateRequest) Reset() {
	*x = CreateRequest{}
	mi := &file_report_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateRequest) ProtoMessage() {}

func (x *CreateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateRequest.ProtoReflect.Descriptor instead.
func (*CreateRequest) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{1}
}

func (x *CreateRequest) GetContentType() ReportedContentType {
	if x != nil {
		return x.ContentType
	}
	return ReportedContentType_REPORTED_CONTENT_TYPE_UNSPECIFIED
}

func (x *CreateRequest) GetContentId() string {
	if x != nil {
		return x.ContentId
	}
	return ""
}

func (x *CreateRequest) GetReason() ReportReason {
	if x != nil {
		return x.Reason
	}
	return ReportReason_REPORT_REASON_UNSPECIFIED
}

func (x *CreateRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

type CreateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *Report                `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateResponse) Reset() {
	*x = CreateResponse{}
	mi := &file_report_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateResponse) ProtoMessage() {}

func (x *CreateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateResponse.ProtoReflect.Descriptor instead.
func (*CreateResponse) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{2}
}

func (x *CreateResponse) GetReport() *Report {
	if x != nil {
		return x.Report
	}
	return nil
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReportId      string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_report_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{3}
}

func (x *GetRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

type GetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *Report                `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetResponse) Reset() {
	*x = GetResponse{}
	mi := &file_report_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetResponse) ProtoMessage() {}

func (x *GetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetResponse.ProtoReflect.Descriptor instead.
func (*GetResponse) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{4}
}

func (x *GetResponse) GetReport() *Report {
	if x != nil {
		return x.Report
	}
	return nil
}

type ListRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	StatusFilter      *ReportStatus          `protobuf:"varint,1,opt,name=status_filter,json=statusFilter,proto3,enum=proto.ReportStatus,oneof" json:"status_filter,omitempty"`
	ContentTypeFilter *ReportedContentType   `protobuf:"varint,2,opt,name=content_type_filter,json=contentTypeFilter,proto3,enum=proto.ReportedContentType,oneof" json:"content_type_filter,omitempty"`
	Cursor            string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit             int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ListRequest) Reset() {
	*x = ListRequest{}
	mi := &file_report_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListRequest) ProtoMessage() {}

func (x *ListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListRequest.ProtoReflect.Descriptor instead.
func (*ListRequest) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{5}
}

func (x *ListRequest) GetStatusFilter() ReportStatus {
	if x != nil && x.StatusFilter != nil {
		return *x.StatusFilter
	}
	return ReportStatus_REPORT_STATUS_UNSPECIFIED
}

func (x *ListRequest) GetContentTypeFilter() ReportedContentType {
	if x != nil && x.ContentTypeFilter != nil {
		return *x.ContentTypeFilter
	}
	return ReportedContentType_REPORTED_CONTENT_TYPE_UNSPECIFIED
}

func (x *ListRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *ListRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type ListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Reports       []*Report              `protobuf:"bytes,1,rep,name=reports,proto3" json:"reports,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListResponse) Reset() {
	*x = ListResponse{}
	mi := &file_report_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListResponse) ProtoMessage() {}

func (x *ListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListResponse.ProtoReflect.Descriptor instead.
func (*ListResponse) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{6}
}

func (x *ListResponse) GetReports() []*Report {
	if x != nil {
		return x.Reports
	}
	return nil
}

func (x *ListResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *ListResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type ResolveRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	ReportId       string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	ResolutionNote *string                `protobuf:"bytes,2,opt,name=resolution_note,json=resolutionNote,proto3,oneof" json:"resolution_note,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ResolveRequest) Reset() {
	*x = ResolveRequest{}
	mi := &file_report_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveRequest) ProtoMessage() {}

func (x *ResolveRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveRequest.ProtoReflect.Descriptor instead.
func (*ResolveRequest) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{7}
}

func (x *ResolveRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *ResolveRequest) GetResolutionNote() string {
	if x != nil && x.ResolutionNote != nil {
		return *x.ResolutionNote
	}
	return ""
}

type ResolveResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *Report                `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResolveResponse) Reset() {
	*x = ResolveResponse{}
	mi := &file_report_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResolveResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResolveResponse) ProtoMessage() {}

func (x *ResolveResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResolveResponse.ProtoReflect.Descriptor instead.
func (*ResolveResponse) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{8}
}

func (x *ResolveResponse) GetReport() *Report {
	if x != nil {
		return x.Report
	}
	return nil
}

type DismissRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ReportId        string                 `protobuf:"bytes,1,opt,name=report_id,json=reportId,proto3" json:"report_id,omitempty"`
	DismissalReason *string                `protobuf:"bytes,2,opt,name=dismissal_reason,json=dismissalReason,proto3,oneof" json:"dismissal_reason,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *DismissRequest) Reset() {
	*x = DismissRequest{}
	mi := &file_report_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DismissRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DismissRequest) ProtoMessage() {}

func (x *DismissRequest) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DismissRequest.ProtoReflect.Descriptor instead.
func (*DismissRequest) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{9}
}

func (x *DismissRequest) GetReportId() string {
	if x != nil {
		return x.ReportId
	}
	return ""
}

func (x *DismissRequest) GetDismissalReason() string {
	if x != nil && x.DismissalReason != nil {
		return *x.DismissalReason
	}
	return ""
}

type DismissResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Report        *Report                `protobuf:"bytes,1,opt,name=report,proto3" json:"report,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DismissResponse) Reset() {
	*x = DismissResponse{}
	mi := &file_report_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DismissResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DismissResponse) ProtoMessage() {}

func (x *DismissResponse) ProtoReflect() protoreflect.Message {
	mi := &file_report_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DismissResponse.ProtoReflect.Descriptor instead.
func (*DismissResponse) Descriptor() ([]byte, []int) {
	return file_report_proto_rawDescGZIP(), []int{10}
}

func (x *DismissResponse) GetReport() *Report {
	if x != nil {
		return x.Report
	}
	return nil
}

var File_report_proto protoreflect.FileDescriptor

const file_report_proto_rawDesc = "" +
	"\n" +
	"\freport.proto\x12\x05proto\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/api/annotations.proto\"\x8d\x05\n" +
	"\x06Report\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1f\n" +
	"\vreporter_id\x18\x02 \x01(\tR\n" +
	"reporterId\x12+\n" +
	"\x11reporter_username\x18\x03 \x01(\tR\x10reporterUsername\x12=\n" +
	"\fcontent_type\x18\x04 \x01(\x0e2\x1a.proto.ReportedContentTypeR\vcontentType\x12\x1d\n" +
	"\n" +
	"content_id\x18\x05 \x01(\tR\tcontentId\x12+\n" +
	"\x06reason\x18\x06 \x01(\x0e2\x13.proto.ReportReasonR\x06reason\x12 \n" +
	"\vdescription\x18\a \x01(\tR\vdescription\x12+\n" +
	"\x06status\x18\b \x01(\x0e2\x13.proto.ReportStatusR\x06status\x12$\n" +
	"\vresolver_id\x18\t \x01(\tH\x00R\n" +
	"resolverId\x88\x01\x01\x120\n" +
	"\x11resolver_username\x18\n" +
	" \x01(\tH\x01R\x10resolverUsername\x88\x01\x01\x12,\n" +
	"\x0fresolution_note\x18\v \x01(\tH\x02R\x0eresolutionNote\x88\x01\x01\x129\n" +
	"\n" +
	"created_at\x18\f \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12@\n" +
	"\vresolved_at\x18\r \x01(\v2\x1a.google.protobuf.TimestampH\x03R\n" +
	"resolvedAt\x88\x01\x01B\x0e\n" +
	"\f_resolver_idB\x14\n" +
	"\x12_resolver_usernameB\x12\n" +
	"\x10_resolution_noteB\x0e\n" +
	"\f_resolved_at\"\xbc\x01\n" +
	"\rCreateRequest\x12=\n" +
	"\fcontent_type\x18\x01 \x01(\x0e2\x1a.proto.ReportedContentTypeR\vcontentType\x12\x1d\n" +
	"\n" +
	"content_id\x18\x02 \x01(\tR\tcontentId\x12+\n" +
	"\x06reason\x18\x03 \x01(\x0e2\x13.proto.ReportReasonR\x06reason\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\"7\n" +
	"\x0eCreateResponse\x12%\n" +
	"\x06report\x18\x01 \x01(\v2\r.proto.ReportR\x06report\")\n" +
	"\n" +
	"GetRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\"4\n" +
	"\vGetResponse\x12%\n" +
	"\x06report\x18\x01 \x01(\v2\r.proto.ReportR\x06report\"\xf5\x01\n" +
	"\vListRequest\x12=\n" +
	"\rstatus_filter\x18\x01 \x01(\x0e2\x13.proto.ReportStatusH\x00R\fstatusFilter\x88\x01\x01\x12O\n" +
	"\x13content_type_filter\x18\x02 \x01(\x0e2\x1a.proto.ReportedContentTypeH\x01R\x11contentTypeFilter\x88\x01\x01\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limitB\x10\n" +
	"\x0e_status_filterB\x16\n" +
	"\x14_content_type_filter\"s\n" +
	"\fListResponse\x12'\n" +
	"\areports\x18\x01 \x03(\v2\r.proto.ReportR\areports\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore\"o\n" +
	"\x0eResolveRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12,\n" +
	"\x0fresolution_note\x18\x02 \x01(\tH\x00R\x0eresolutionNote\x88\x01\x01B\x12\n" +
	"\x10_resolution_note\"8\n" +
	"\x0fResolveResponse\x12%\n" +
	"\x06report\x18\x01 \x01(\v2\r.proto.ReportR\x06report\"r\n" +
	"\x0eDismissRequest\x12\x1b\n" +
	"\treport_id\x18\x01 \x01(\tR\breportId\x12.\n" +
	"\x10dismissal_reason\x18\x02 \x01(\tH\x00R\x0fdismissalReason\x88\x01\x01B\x13\n" +
	"\x11_dismissal_reason\"8\n" +
	"\x0fDismissResponse\x12%\n" +
	"\x06report\x18\x01 \x01(\v2\r.proto.ReportR\x06report*\xfd\x01\n" +
	"\fReportReason\x12\x1d\n" +
	"\x19REPORT_REASON_UNSPECIFIED\x10\x00\x12\x16\n" +
	"\x12REPORT_REASON_SPAM\x10\x01\x12\x1c\n" +
	"\x18REPORT_REASON_HARASSMENT\x10\x02\x12 \n" +
	"\x1cREPORT_REASON_MISINFORMATION\x10\x03\x12\"\n" +
	"\x1eREPORT_REASON_EXPLICIT_CONTENT\x10\x04\x12\x1a\n" +
	"\x16REPORT_REASON_VIOLENCE\x10\x05\x12\x1d\n" +
	"\x19REPORT_REASON_HATE_SPEECH\x10\x06\x12\x17\n" +
	"\x13REPORT_REASON_OTHER\x10\a*\x81\x01\n" +
	"\fReportStatus\x12\x1d\n" +
	"\x19REPORT_STATUS_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15REPORT_STATUS_PENDING\x10\x01\x12\x1a\n" +
	"\x16REPORT_STATUS_RESOLVED\x10\x02\x12\x1b\n" +
	"\x17REPORT_STATUS_DISMISSED\x10\x03*\x7f\n" +
	"\x13ReportedContentType\x12%\n" +
	"!REPORTED_CONTENT_TYPE_UNSPECIFIED\x10\x00\x12\x1e\n" +
	"\x1aREPORTED_CONTENT_TYPE_POST\x10\x01\x12!\n" +
	"\x1dREPORTED_CONTENT_TYPE_COMMENT\x10\x022\xb0\x03\n" +
	"\rReportService\x12J\n" +
	"\x06Create\x12\x14.proto.CreateRequest\x1a\x15.proto.CreateResponse\"\x13\x82\xd3\xe4\x93\x02\r:\x01*\"\b/reports\x12J\n" +
	"\x03Get\x12\x11.proto.GetRequest\x1a\x12.proto.GetResponse\"\x1c\x82\xd3\xe4\x93\x02\x16\x12\x14/reports/{report_id}\x12A\n" +
	"\x04List\x12\x12.proto.ListRequest\x1a\x13.proto.ListResponse\"\x10\x82\xd3\xe4\x93\x02\n" +
	"\x12\b/reports\x12a\n" +
	"\aResolve\x12\x15.proto.ResolveRequest\x1a\x16.proto.ResolveResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/reports/{report_id}/resolve\x12a\n" +
	"\aDismiss\x12\x15.proto.DismissRequest\x1a\x16.proto.DismissResponse\"'\x82\xd3\xe4\x93\x02!:\x01*\"\x1c/reports/{report_id}/dismissB\bZ\x06/protob\x06proto3"

var (
	file_report_proto_rawDescOnce sync.Once
	file_report_proto_rawDescData []byte
)

func file_report_proto_rawDescGZIP() []byte {
	file_report_proto_rawDescOnce.Do(func() {
		file_report_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_report_proto_rawDesc), len(file_report_proto_rawDesc)))
	})
	return file_report_proto_rawDescData
}

var file_report_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_report_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_report_proto_goTypes = []any{
	(ReportReason)(0),             // 0: proto.ReportReason
	(ReportStatus)(0),             // 1: proto.ReportStatus
	(ReportedContentType)(0),      // 2: proto.ReportedContentType
	(*Report)(nil),                // 3: proto.Report
	(*CreateRequest)(nil),         // 4: proto.CreateRequest
	(*CreateResponse)(nil),        // 5: proto.CreateResponse
	(*GetRequest)(nil),            // 6: proto.GetRequest
	(*GetResponse)(nil),           // 7: proto.GetResponse
	(*ListRequest)(nil),           // 8: proto.ListRequest
	(*ListResponse)(nil),          // 9: proto.ListResponse
	(*ResolveRequest)(nil),        // 10: proto.ResolveRequest
	(*ResolveResponse)(nil),       // 11: proto.ResolveResponse
	(*DismissRequest)(nil),        // 12: proto.DismissRequest
	(*DismissResponse)(nil),       // 13: proto.DismissResponse
	(*timestamppb.Timestamp)(nil), // 14: google.protobuf.Timestamp
}
var file_report_proto_depIdxs = []int32{
	2,  // 0: proto.Report.content_type:type_name -> proto.ReportedContentType
	0,  // 1: proto.Report.reason:type_name -> proto.ReportReason
	1,  // 2: proto.Report.status:type_name -> proto.ReportStatus
	14, // 3: proto.Report.created_at:type_name -> google.protobuf.Timestamp
	14, // 4: proto.Report.resolved_at:type_name -> google.protobuf.Timestamp
	2,  // 5: proto.CreateRequest.content_type:type_name -> proto.ReportedContentType
	0,  // 6: proto.CreateRequest.reason:type_name -> proto.ReportReason
	3,  // 7: proto.CreateResponse.report:type_name -> proto.Report
	3,  // 8: proto.GetResponse.report:type_name -> proto.Report
	1,  // 9: proto.ListRequest.status_filter:type_name -> proto.ReportStatus
	2,  // 10: proto.ListRequest.content_type_filter:type_name -> proto.ReportedContentType
	3,  // 11: proto.ListResponse.reports:type_name -> proto.Report
	3,  // 12: proto.ResolveResponse.report:type_name -> proto.Report
	3,  // 13: proto.DismissResponse.report:type_name -> proto.Report
	4,  // 14: proto.ReportService.Create:input_type -> proto.CreateRequest
	6,  // 15: proto.ReportService.Get:input_type -> proto.GetRequest
	8,  // 16: proto.ReportService.List:input_type -> proto.ListRequest
	10, // 17: proto.ReportService.Resolve:input_type -> proto.ResolveRequest
	12, // 18: proto.ReportService.Dismiss:input_type -> proto.DismissRequest
	5,  // 19: proto.ReportService.Create:output_type -> proto.CreateResponse
	7,  // 20: proto.ReportService.Get:output_type -> proto.GetResponse
	9,  // 21: proto.ReportService.List:output_type -> proto.ListResponse
	11, // 22: proto.ReportService.Resolve:output_type -> proto.ResolveResponse
	13, // 23: proto.ReportService.Dismiss:output_type -> proto.DismissResponse
	19, // [19:24] is the sub-list for method output_type
	14, // [14:19] is the sub-list for method input_type
	14, // [14:14] is the sub-list for extension type_name
	14, // [14:14] is the sub-list for extension extendee
	0,  // [0:14] is the sub-list for field type_name
}

func init() { file_report_proto_init() }
func file_report_proto_init() {
	if File_report_proto != nil {
		return
	}
	file_report_proto_msgTypes[0].OneofWrappers = []any{}
	file_report_proto_msgTypes[5].OneofWrappers = []any{}
	file_report_proto_msgTypes[7].OneofWrappers = []any{}
	file_report_proto_msgTypes[9].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_report_proto_rawDesc), len(file_report_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_report_proto_goTypes,
		DependencyIndexes: file_report_proto_depIdxs,
		EnumInfos:         file_report_proto_enumTypes,
		MessageInfos:      file_report_proto_msgTypes,
	}.Build()
	File_report_proto = out.File
	file_report_proto_goTypes = nil
	file_report_proto_depIdxs = nil
}
