// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.31.1
// source: search.proto

package proto

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ContentType int32

const (
	ContentType_CONTENT_TYPE_UNSPECIFIED ContentType = 0
	ContentType_CONTENT_TYPE_COMMUNITIES ContentType = 1
	ContentType_CONTENT_TYPE_POSTS       ContentType = 2
	ContentType_CONTENT_TYPE_COMMENTS    ContentType = 3
	ContentType_CONTENT_TYPE_USERS       ContentType = 4
	ContentType_CONTENT_TYPE_ALL         ContentType = 5
)

// Enum value maps for ContentType.
var (
	ContentType_name = map[int32]string{
		0: "CONTENT_TYPE_UNSPECIFIED",
		1: "CONTENT_TYPE_COMMUNITIES",
		2: "CONTENT_TYPE_POSTS",
		3: "CONTENT_TYPE_COMMENTS",
		4: "CONTENT_TYPE_USERS",
		5: "CONTENT_TYPE_ALL",
	}
	ContentType_value = map[string]int32{
		"CONTENT_TYPE_UNSPECIFIED": 0,
		"CONTENT_TYPE_COMMUNITIES": 1,
		"CONTENT_TYPE_POSTS":       2,
		"CONTENT_TYPE_COMMENTS":    3,
		"CONTENT_TYPE_USERS":       4,
		"CONTENT_TYPE_ALL":         5,
	}
)

func (x ContentType) Enum() *ContentType {
	p := new(ContentType)
	*p = x
	return p
}

func (x ContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_search_proto_enumTypes[0].Descriptor()
}

func (ContentType) Type() protoreflect.EnumType {
	return &file_search_proto_enumTypes[0]
}

func (x ContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentType.Descriptor instead.
func (ContentType) EnumDescriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{0}
}

type SearchResult struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Result:
	//
	//	*SearchResult_Community
	//	*SearchResult_Post
	//	*SearchResult_Comment
	//	*SearchResult_User
	Result         isSearchResult_Result `protobuf_oneof:"result"`
	RelevanceScore float32               `protobuf:"fixed32,5,opt,name=relevance_score,json=relevanceScore,proto3" json:"relevance_score,omitempty"` // TODO:
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SearchResult) Reset() {
	*x = SearchResult{}
	mi := &file_search_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResult) ProtoMessage() {}

func (x *SearchResult) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResult.ProtoReflect.Descriptor instead.
func (*SearchResult) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{0}
}

func (x *SearchResult) GetResult() isSearchResult_Result {
	if x != nil {
		return x.Result
	}
	return nil
}

func (x *SearchResult) GetCommunity() *Community {
	if x != nil {
		if x, ok := x.Result.(*SearchResult_Community); ok {
			return x.Community
		}
	}
	return nil
}

func (x *SearchResult) GetPost() *Post {
	if x != nil {
		if x, ok := x.Result.(*SearchResult_Post); ok {
			return x.Post
		}
	}
	return nil
}

func (x *SearchResult) GetComment() *Comment {
	if x != nil {
		if x, ok := x.Result.(*SearchResult_Comment); ok {
			return x.Comment
		}
	}
	return nil
}

func (x *SearchResult) GetUser() *UserProfile {
	if x != nil {
		if x, ok := x.Result.(*SearchResult_User); ok {
			return x.User
		}
	}
	return nil
}

func (x *SearchResult) GetRelevanceScore() float32 {
	if x != nil {
		return x.RelevanceScore
	}
	return 0
}

type isSearchResult_Result interface {
	isSearchResult_Result()
}

type SearchResult_Community struct {
	Community *Community `protobuf:"bytes,1,opt,name=community,proto3,oneof"`
}

type SearchResult_Post struct {
	Post *Post `protobuf:"bytes,2,opt,name=post,proto3,oneof"`
}

type SearchResult_Comment struct {
	Comment *Comment `protobuf:"bytes,3,opt,name=comment,proto3,oneof"`
}

type SearchResult_User struct {
	User *UserProfile `protobuf:"bytes,4,opt,name=user,proto3,oneof"`
}

func (*SearchResult_Community) isSearchResult_Result() {}

func (*SearchResult_Post) isSearchResult_Result() {}

func (*SearchResult_Comment) isSearchResult_Result() {}

func (*SearchResult_User) isSearchResult_Result() {}

type SearchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ContentType   ContentType            `protobuf:"varint,1,opt,name=content_type,json=contentType,proto3,enum=proto.ContentType" json:"content_type,omitempty"`
	Query         string                 `protobuf:"bytes,2,opt,name=query,proto3" json:"query,omitempty"` // min 3 chars
	Cursor        string                 `protobuf:"bytes,3,opt,name=cursor,proto3" json:"cursor,omitempty"`
	Limit         int32                  `protobuf:"varint,4,opt,name=limit,proto3" json:"limit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchRequest) Reset() {
	*x = SearchRequest{}
	mi := &file_search_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchRequest) ProtoMessage() {}

func (x *SearchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchRequest.ProtoReflect.Descriptor instead.
func (*SearchRequest) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{1}
}

func (x *SearchRequest) GetContentType() ContentType {
	if x != nil {
		return x.ContentType
	}
	return ContentType_CONTENT_TYPE_UNSPECIFIED
}

func (x *SearchRequest) GetQuery() string {
	if x != nil {
		return x.Query
	}
	return ""
}

func (x *SearchRequest) GetCursor() string {
	if x != nil {
		return x.Cursor
	}
	return ""
}

func (x *SearchRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

type SearchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Results       []*SearchResult        `protobuf:"bytes,1,rep,name=results,proto3" json:"results,omitempty"`
	NextCursor    string                 `protobuf:"bytes,2,opt,name=next_cursor,json=nextCursor,proto3" json:"next_cursor,omitempty"`
	HasMore       bool                   `protobuf:"varint,3,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchResponse) Reset() {
	*x = SearchResponse{}
	mi := &file_search_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchResponse) ProtoMessage() {}

func (x *SearchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_search_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchResponse.ProtoReflect.Descriptor instead.
func (*SearchResponse) Descriptor() ([]byte, []int) {
	return file_search_proto_rawDescGZIP(), []int{2}
}

func (x *SearchResponse) GetResults() []*SearchResult {
	if x != nil {
		return x.Results
	}
	return nil
}

func (x *SearchResponse) GetNextCursor() string {
	if x != nil {
		return x.NextCursor
	}
	return ""
}

func (x *SearchResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

var File_search_proto protoreflect.FileDescriptor

const file_search_proto_rawDesc = "" +
	"\n" +
	"\fsearch.proto\x12\x05proto\x1a\fentity.proto\x1a\x1cgoogle/api/annotations.proto\"\xec\x01\n" +
	"\fSearchResult\x120\n" +
	"\tcommunity\x18\x01 \x01(\v2\x10.proto.CommunityH\x00R\tcommunity\x12!\n" +
	"\x04post\x18\x02 \x01(\v2\v.proto.PostH\x00R\x04post\x12*\n" +
	"\acomment\x18\x03 \x01(\v2\x0e.proto.CommentH\x00R\acomment\x12(\n" +
	"\x04user\x18\x04 \x01(\v2\x12.proto.UserProfileH\x00R\x04user\x12'\n" +
	"\x0frelevance_score\x18\x05 \x01(\x02R\x0erelevanceScoreB\b\n" +
	"\x06result\"\x8a\x01\n" +
	"\rSearchRequest\x125\n" +
	"\fcontent_type\x18\x01 \x01(\x0e2\x12.proto.ContentTypeR\vcontentType\x12\x14\n" +
	"\x05query\x18\x02 \x01(\tR\x05query\x12\x16\n" +
	"\x06cursor\x18\x03 \x01(\tR\x06cursor\x12\x14\n" +
	"\x05limit\x18\x04 \x01(\x05R\x05limit\"{\n" +
	"\x0eSearchResponse\x12-\n" +
	"\aresults\x18\x01 \x03(\v2\x13.proto.SearchResultR\aresults\x12\x1f\n" +
	"\vnext_cursor\x18\x02 \x01(\tR\n" +
	"nextCursor\x12\x19\n" +
	"\bhas_more\x18\x03 \x01(\bR\ahasMore*\xaa\x01\n" +
	"\vContentType\x12\x1c\n" +
	"\x18CONTENT_TYPE_UNSPECIFIED\x10\x00\x12\x1c\n" +
	"\x18CONTENT_TYPE_COMMUNITIES\x10\x01\x12\x16\n" +
	"\x12CONTENT_TYPE_POSTS\x10\x02\x12\x19\n" +
	"\x15CONTENT_TYPE_COMMENTS\x10\x03\x12\x16\n" +
	"\x12CONTENT_TYPE_USERS\x10\x04\x12\x14\n" +
	"\x10CONTENT_TYPE_ALL\x10\x052W\n" +
	"\rSearchService\x12F\n" +
	"\x06Search\x12\x14.proto.SearchRequest\x1a\x15.proto.SearchResponse\"\x0f\x82\xd3\xe4\x93\x02\t\x12\a/searchB\bZ\x06/protob\x06proto3"

var (
	file_search_proto_rawDescOnce sync.Once
	file_search_proto_rawDescData []byte
)

func file_search_proto_rawDescGZIP() []byte {
	file_search_proto_rawDescOnce.Do(func() {
		file_search_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_search_proto_rawDesc), len(file_search_proto_rawDesc)))
	})
	return file_search_proto_rawDescData
}

var file_search_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_search_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_search_proto_goTypes = []any{
	(ContentType)(0),       // 0: proto.ContentType
	(*SearchResult)(nil),   // 1: proto.SearchResult
	(*SearchRequest)(nil),  // 2: proto.SearchRequest
	(*SearchResponse)(nil), // 3: proto.SearchResponse
	(*Community)(nil),      // 4: proto.Community
	(*Post)(nil),           // 5: proto.Post
	(*Comment)(nil),        // 6: proto.Comment
	(*UserProfile)(nil),    // 7: proto.UserProfile
}
var file_search_proto_depIdxs = []int32{
	4, // 0: proto.SearchResult.community:type_name -> proto.Community
	5, // 1: proto.SearchResult.post:type_name -> proto.Post
	6, // 2: proto.SearchResult.comment:type_name -> proto.Comment
	7, // 3: proto.SearchResult.user:type_name -> proto.UserProfile
	0, // 4: proto.SearchRequest.content_type:type_name -> proto.ContentType
	1, // 5: proto.SearchResponse.results:type_name -> proto.SearchResult
	2, // 6: proto.SearchService.Search:input_type -> proto.SearchRequest
	3, // 7: proto.SearchService.Search:output_type -> proto.SearchResponse
	7, // [7:8] is the sub-list for method output_type
	6, // [6:7] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_search_proto_init() }
func file_search_proto_init() {
	if File_search_proto != nil {
		return
	}
	file_entity_proto_init()
	file_search_proto_msgTypes[0].OneofWrappers = []any{
		(*SearchResult_Community)(nil),
		(*SearchResult_Post)(nil),
		(*SearchResult_Comment)(nil),
		(*SearchResult_User)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_search_proto_rawDesc), len(file_search_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_search_proto_goTypes,
		DependencyIndexes: file_search_proto_depIdxs,
		EnumInfos:         file_search_proto_enumTypes,
		MessageInfos:      file_search_proto_msgTypes,
	}.Build()
	File_search_proto = out.File
	file_search_proto_goTypes = nil
	file_search_proto_depIdxs = nil
}
